feat: clean up eslint errors and warnings
icssc/AntAlmanac pull request #1000
Opened 2024-08-20 05:36 UTC by KevinWu098

## Summary
> ✖ 101 problems (66 errors, 35 warnings)
  59 errors and 2 warnings potentially fixable with the `--fix` option.

> ✖ 3 problems (0 errors, 3 warnings)

1. This PR resolves almost 100 eslint problems (the remainder are ones where I didn't feel confident touching on components relating to `Map`) 
2. Broadly, most of these errors and warnings fall into a few buckets:
    - Import Order
    - Default Exports
    - Type errors (`any`)
    - Exhaustive Deps

## Test Plan
1. These changes do span a lot of files, but no business logic has been changed (aside from useEffect/useCallback dependencies). Potential tests would just be clicking around and validating big features haven't regressed

2024-09-30 20:03 UTC, ap0nia requested changes
1. Why are we importing types from `react` instead of using the global `React` namespace. If `eslint` is unable to detect this global namespace, then we need to fix the configuration.
2. Please specify imports as types wherever relevant. This should ideally be enforced via `tsconfig`, but it is not. You don't have to apply this rule across the entire codebase, but at least for the changes you're applying in this PR.
3. Please confirm that the map works as expected. Leaflet is generally a very janky library that heavily relies on the use of `window` globals to work.

2024-09-30 20:03 UTC, ap0nia commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx
> +import { ChangeEvent, PureComponent } from 'react';
Did you intentionally import `ChangeEvent`? The `React` namescope should be available globally in React projects, and it's easier to use `React.ChangeEvent` for types.

```suggestion
import { type ChangeEvent, PureComponent } from 'react';
```

2024-09-30 20:03 UTC, ap0nia commented on apps/antalmanac/src/components/Calendar/Toolbar/EditSchedule/ScheduleNameDialog.tsx
> +import { forwardRef, useCallback, useState, useMemo, MouseEvent, ChangeEvent, KeyboardEvent } from 'react';
I'll recap this in the overall review as well, but please distinguish between type imports and named imports whenever possible.

```suggestion
import { forwardRef, useCallback, useState, useMemo, type MouseEvent, type ChangeEvent, type KeyboardEvent } from 'react';
```

2024-09-30 20:03 UTC, ap0nia commented on apps/antalmanac/src/components/Calendar/Toolbar/EditSchedule/ScheduleNameDialog.tsx
> +        (event: MouseEvent<HTMLLIElement>) => {
Strongly typing the generic when you don't need it is just superfluous.

```suggestion
        (event: MouseEvent) => {
```

2024-09-30 20:03 UTC, ap0nia commented on apps/antalmanac/src/components/Map/Routes.tsx
Maps are very finnicky, please double check that it continues to work after these changes. `import L from 'leaflet'` is how imports are done based on all documentation and references to leaflet.
Ideally, they'd be able handle different environments slightly better, but I'm not sure if they do :^)

2024-09-30 20:03 UTC, ap0nia commented on apps/antalmanac/src/components/RightPane/SectionTable/SectionTable.types.ts
>  import { AACourse } from '@packages/antalmanac-types';
```suggestion
import type { AACourse } from '@packages/antalmanac-types';
```

2024-09-30 20:03 UTC, ap0nia commented on apps/antalmanac/src/components/inputs/building-select.tsx
> +        [props]
This is bad; don't pass the entire props object because the reference is not stable. Specify the property, via destructuring is best.
I'm pretty sure I'm the one that did this, so this is a note for my past self.

```tsx
function MyComponent(props) {
  const { a, b, c } = props

  const memoizedThing = useMemo(() => {}, [a, b, c])
}
```

*In more depth*
Whenever the parent component re-renders, a new "props" object is constructed and passed to the child. The props object can have the same values as the props object from the previous render, but it's a different entity in memory. If you attempt to use the "props" object as a dependency for memo-ization, it should not be effective because it changes; you want to refer to primitive values within the object explicitly.

2024-09-30 20:03 UTC, ap0nia commented on apps/antalmanac/src/lib/helpers.ts
>  export async function queryGraphQL<PromiseReturnType>(queryString: string): Promise<PromiseReturnType | null> {
On a side note, this is a completely useless use of generics.

```ts
const result = queryGraphQL<string>()

const result: string = queryGraphQL()
```

In both scenarios, you have to explicitly type the result anyways. It's just that when you use generics, the function signature is "more complex" and doesn't provide you any type safety or DX in anyway.

2024-10-02 09:07 UTC, KevinWu098 commented on apps/antalmanac/src/components/Map/Routes.tsx
Checked on mobile and on desktop (Safari, Chrome, respectively) and the map is still working as expected! I'm happy to revert the changes to the Map though -- don't fix what ain't broke -- if you think it's too risky

2024-10-24 16:29 UTC, MinhxNguyen7 approved these changes
Seems alright

2024-10-24 16:31 UTC, merged