feat: changing pop-over x button for hover :) and adding  padding to the popover to make it more visible
icssc/AntAlmanac pull request #1012
Opened 2024-10-16 20:43 UTC by Priyansh4444

## Summary
Making the UX just a bit better by creating a transition for the hover on the button

## Test Plan
Running the frontend 

## Issues
- Currently the 4th item on the path goes a bit too left on the screen
- Some steps also go a bit off the page

Closes #1011

2024-10-17 05:51 UTC, MinhxNguyen7 requested changes
Thanks for your contribution! 

Code-wise, the button should not be defined with the router; that just doesn't make logical sense. it should go in `components/buttons`. Also, since we drink the MUI Kool-Aid, we shouldn't have to implement such a simple button. Take a look at [this](https://mui.com/material-ui/react-button/). We should be able to just define the button in-line with some customization. Do say though, if that is not fit-for-purpose.

I have a few things to ask in terms of documentation. These are somewhat matters of pedantry, but I think it's important to maintain standards.

Could you please give more information on the test plan? Yes, we run the front end, but what should we expect to see? You also say that there are some problems. Was that introduced by this PR, or was it there before? If the former is the case, why can't it be addressed? If the latter is the case, you should put that in a "Future Follow-Up" section and add it as an issue.

Also, the "Issues" section is for related GitHub issues. The issues that you have there should go in the summary.

2024-10-17 06:40 UTC, Priyansh4444 commented
Thank you for the feedback I will keep this in mind going on when I contribute to other repositories as well!
I think it is fit to make its own component for the button.
There are two ways to edit the button, either by adding it as a component in styles or making a react functional component for it.

I think the MUI button is the best way to approach the matter since the onHover Effect then can be achieved!
though another solution could potentially be manaully taking the ``.react__tour_close`` class and adding it to App.css

I am still a bit unsure, how to test frontend other than visually, but in terms of expected result having the tourguide is partially going out of bounds of the screen and therefore cannot be seen I am unsure how to control where the tourguide goes. 
The problems I mentioned happens before the PR as well. I will try and fix these issues when I get a bit more time since currently I am a bit busy!


Future Follow Up:
- Fixing the TourGuide So it does not go out of bounds
- Making the 4th step of the tour guide happen to the right of the calendar instead of left (it was on the right before the PR)

2024-11-29 11:44 UTC, Priyansh4444 commented
I have no idea how to test the front-end other than visually, and visually speaking I think its working and does a good job formatting the X button, any thoughts and guidance would be appreciated!

2025-02-02 00:56 UTC, KevinWu098 commented
Closing this PR on staleness. If you feel strongly about the PR, please feel free to open the PR again.

My personal recommendation would be to take a simpler approach:

<img width="465" alt="Screenshot 2025-02-01 at 4 50 17 PM" src="https://github.com/user-attachments/assets/a14d1b85-ae80-4530-a270-2fdd3a91e3a9" />

By just adjusting the tourguide styles slightly, we can prevent the textwrap and position the button in a much clearer, overlap-free position. 
```
// reactour__popover
padding: 24px

// reactour__close-button
top: 8px;
right: 8px;
width: 8px;
height: 8px;
```

This isn't saying that a custom component isn't an equally valid solution, but because this PR regresses the tour in terms of introducing clipping and a somewhat unruly component (e.g. LOC dedicated to styling, see below), we can't accept the PR in the direction that it's currently headed.

```
                                marginLeft: 10,
                                marginRight: 10,
                                marginTop: 10,
                                marginBottom: 10,
                                paddingTop: 20,
                                paddingBottom: 20,
                                paddingLeft: 35,
                                paddingRight: 35,
```

2025-02-02 00:56 UTC, closed without merging