feat: encode/decode advanced search in URL
icssc/AntAlmanac pull request #1013
Opened 2024-10-24 16:51 UTC by KevinWu098

## Summary

## Test Plan

## Issues

Closes #

2024-10-24 18:01 UTC, MinhxNguyen7 commented
What's the purpose of this? Wouldn't the feature be that, when you search, you can share the URL with someone else?

Technically speaking, this is a valid PR, but it should be a little more. It should close #558. At the very least, all the params, not just the advanced search, should be sharable.

Furthermore, there should be a `/search` route where it actually executes the search, falling to the search screen conditionally if the params are insufficient. Allowing people to share or bookmark the link to a search would be very useful. That would be quite a bit of additional work, but you should do that if you're up for it.

2024-10-24 19:11 UTC, KevinWu098 commented
> Technically speaking, this is a valid PR, but it should be a little more. It should close #558. At the very least, all the params, not just the advanced search, should be sharable.
> 
> Furthermore, there should be a `/search` route where it actually executes the search, falling to the search screen conditionally if the params are insufficient. Allowing people to share or bookmark the link to a search would be very useful. That would be quite a bit of additional work, but you should do that if you're up for it.

Just pushed a commit that will search if it detects params; also, all the params as of this PR should be sharable -- #546 encodes manual search params

2024-11-06 04:11 UTC, MinhxNguyen7 requested changes
Mostly looks good, but it looks like it *sometimes* executes the search, and sometimes incorrectly. See this case: https://staging-1013.antalmanac.com/?GE=GE-3&instructor=ihler

2024-11-06 04:13 UTC, KevinWu098 commented
> Mostly looks good, but it looks like it _sometimes_ executes the search, and sometimes incorrectly. See this case: https://staging-1013.antalmanac.com/?GE=GE-3&instructor=ihler

Hm, I might not have tried it out enough, but I'm not seeing any unexpected behavior (aside from the Grades toast error, though I feel like that might be more related to us going from F24 -> W25?)

2024-11-06 04:42 UTC, MinhxNguyen7 commented
That's a GE-3 search, and the results are upper divs, which are not GEs

2024-11-07 00:20 UTC, KevinWu098 commented
> That's a GE-3 search, and the results are upper divs, which are not GEs

Thanks for the catch -- was reading ge from the url incorrectly :)

2024-11-14 04:59 UTC, MinhxNguyen7 approved these changes
I'm not 100% convinced considering we've only tested it a little, but it can't break UX that badly.

2024-11-14 04:59 UTC, merged