968 create error page
icssc/AntAlmanac pull request #1035
Opened 2024-11-17 20:09 UTC by alexespejo

## Summary
Created a custom error page that displays when a user encounters an error or enters a bad route 

## Issues
In dark mode the link text color poorly contrasts the gray background 

Closes #

2024-11-17 21:35 UTC, KevinWu098 requested changes
Congrats on your first PR! Mostly looks good to me, with some nitpicks on wording and best practices.

Two main points other than the review comments:
One: If you're feeling up to it, I'd say a centered (but still mobile-friendly) error page would be better suited for making the error page look cleaner (see below)

![image](https://github.com/user-attachments/assets/f9add6ec-dc8d-4274-b779-19fe3e1ec433)

No need to add graphics and whatnot, but centering does make the error page (IMO) feel nicer.


Two: Could you include screenshots of the error page (both light and dark) in your pull request? (it helps your reviewer visually examine the page, although we usually checkout the branch locally as well).

2024-11-17 21:35 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +                This error may be caused by you having an out of date version of AntAlmanac.
```suggestion
                This error may be caused by your browser having an out of date version of AntAlmanac.
```
nit: "you" may feel too direct for users

2024-11-17 21:35 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +            Oops! Something went wrong 🥺 👉👈
```suggestion
            Oops! Something went wrong.
```
nit: 🥺 as much as I'd like to keep the emojis, I think AA broadly tries to maintain a professional tone / communication

2024-11-17 21:35 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +export default ErrorPage;
```suggestion
```
nit: prefer non-default exports (see above)

2024-11-17 21:35 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +const ErrorPage = () => (
```suggestion
export const ErrorPage = () => (
```
nit: prefer exporting non-default components. Although large portions of the AA codebase uses default exports, it's better practice to export (and import) components more explicitly

2024-11-18 00:59 UTC, MinhxNguyen7 requested changes
Also, can you add reproduction information in the description so that reviewer(s) don't have to figure out a way to induce an error? That should be under a section titled "Test Plan". See [this PR](https://github.com/icssc/AntAlmanac/pull/1008) as an example for writing a PR description
Also, please specify which issue it closes there? I know it's in the title, but putting it in the description closes it automatically when the PR merges

2024-11-18 01:37 UTC, alexespejo commented
Edited message (dark and light) 

<img width="1219" alt="image" src="https://github.com/user-attachments/assets/e9d762af-b6e2-4938-a1a3-a1ce2f0d5389">
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/a1f2b0a0-ac7a-4111-830f-4158c6490017">

2024-11-18 01:47 UTC, alexespejo commented
> Also, can you add reproduction information in the description so that reviewer(s) don't have to figure out a way to induce an error? That should be under a section titled "Test Plan". See [this PR](https://github.com/icssc/AntAlmanac/pull/1008) as an example for writing a PR description Also, please specify which issue it closes there? I know it's in the title, but putting it in the description closes it automatically when the PR merges

Is there a known way to reproduce runtime errors like a bad fetch request. In theory the page should appear for all errors but I wanted to see

2024-11-18 06:54 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
Also noting that, if possible, we should also display the actual error that we're catching to the user (so that they can then pass it along to us via screenshot or copy/paste).

2024-11-18 06:56 UTC, KevinWu098 commented
> > Also, can you add reproduction information in the description so that reviewer(s) don't have to figure out a way to induce an error? That should be under a section titled "Test Plan". See [this PR](https://github.com/icssc/AntAlmanac/pull/1008) as an example for writing a PR description Also, please specify which issue it closes there? I know it's in the title, but putting it in the description closes it automatically when the PR merges
> 
> Is there a known way to reproduce runtime errors like a bad fetch request. In theory the page should appear for all errors but I wanted to see

mm, might be a StackOverflow question -- one thing that jumps to mind is just writing in a `throw Error` into any given file!

2024-11-18 07:14 UTC, MinhxNguyen7 commented
> Is there a known way to reproduce runtime errors like a bad fetch request. In theory the page should appear for all errors but I wanted to see

Ah I didn't realize you hadn't figured that.

2024-11-18 07:21 UTC, alexespejo commented
> > > Also, can you add reproduction information in the description so that reviewer(s) don't have to figure out a way to induce an error? That should be under a section titled "Test Plan". See [this PR](https://github.com/icssc/AntAlmanac/pull/1008) as an example for writing a PR description Also, please specify which issue it closes there? I know it's in the title, but putting it in the description closes it automatically when the PR merges
> > 
> > 
> > Is there a known way to reproduce runtime errors like a bad fetch request. In theory the page should appear for all errors but I wanted to see
> 
> mm, might be a StackOverflow question -- one thing that jumps to mind is just writing in a `throw Error` into any given file!

this works

2024-11-20 03:57 UTC, alexespejo commented
New error page displaying the error message. 

The error message can be hidden by default if anyone has a preference

Toggle on 
![image](https://github.com/user-attachments/assets/64787f4b-c921-41d8-b00a-cf808a11acce)
![image](https://github.com/user-attachments/assets/012e8cde-887b-4aa0-808d-d595302e504e)


Toggle off 
![image](https://github.com/user-attachments/assets/0c5ac8a3-0802-458e-a3b7-2abbc6052153)

2024-11-20 06:08 UTC, KevinWu098 requested changes
Looks awesome! Really solid improvement, and will hopefully help our bug reporting user flow.

Could you update your original PR message to
a. Include the latest images
b. Update the `Issues` section to link to the original issue #968 (e.g. `Closes #968`)
    - the issues section isn't really used to state issues about your PR, but rather to just write the issues this PR is related to / closes

Just a couple more nits (I swear I'm not always this pedantic), but otherwise looks solid! Will also ping @MinhxNguyen7 again for another pair of eyes, since this page will be relatively prominent to users.

2024-11-20 06:08 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +import { Link } from 'react-router-dom';
```suggestion
import { Link, useRouteError } from 'react-router-dom';
```
nit: no dupe imports

2024-11-20 06:08 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +export const ErrorPage = () => {
nit: name your file the same as the component (or vice versa)

2024-11-20 06:08 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +                        <pre>{error.stack}</pre> // Display stack trace only in development mode
Is the comment intended? Looks like it's always open?

Regardless, I think we should keep the error message always displayed, as we want users to immediately (and visibly) see the error so they're more likely to pass it along to us.

2024-11-20 06:09 UTC, KevinWu098 commented on apps/antalmanac/src/routes/Error.tsx
> +                    <Link to="https://forms.gle/k81f2aNdpdQYeKK8A">bug report</Link> with the provided error
```suggestion
                    <Link to="https://forms.gle/k81f2aNdpdQYeKK8A">bug report</Link> with the provided error.
```
nit: Missing a period :p

2024-11-20 22:03 UTC, KevinWu098 approved these changes
LGTM, but I'll hold off on approving until Minh or Dalton gets a chance to look at this

2024-11-21 20:58 UTC, MinhxNguyen7 approved these changes

2024-11-21 20:59 UTC, merged