Ensure unique schedule names when adding and renaming.
icssc/AntAlmanac pull request #1049
Opened 2024-11-22 01:23 UTC by vicksey

## Summary
Ensure unique schedule names when adding and renaming.

## Test Plan

## Issues

Closes #

2024-11-22 02:49 UTC, MinhxNguyen7 commented
I take that this is ready for review. Can you add the issue that you're closing in the "Issues" section of the PR? Also, please add a brief test plan for how the reviewer would confirm that your change does what it's supposed to do and probably doesn't break anything.

2024-12-22 23:41 UTC, MinhxNguyen7 requested changes
Can you extract the schedule name field, along with the logic and error messages so that it can be reused?

Also, fixing the merge conflicts should allow the staging instance to deploy successfully.

2024-12-22 23:41 UTC, MinhxNguyen7 commented on apps/antalmanac/src/components/dialogs/AddSchedule.tsx
> +                        error={!!errorMessage}
Please use `Boolean` instead of `!!`. That's less explicit and quite weird to read.

2025-01-15 20:52 UTC, KevinWu098 commented
Closing as completed via #1048

2025-01-15 20:52 UTC, closed without merging