Fixed "Error loading grades information" with empty course code
icssc/AntAlmanac pull request #1056
Opened 2024-11-23 22:47 UTC by IsaacNguyen

## Summary
Refer to #1043 because it's the same issue just with course code.
Error was propagating because course code was not check in this if statement.
![image](https://github.com/user-attachments/assets/be76e17d-3f3a-474f-9a69-00589c080194)

## Test Plan

## Issues

Closes #

2024-11-23 23:07 UTC, alexanderl19 requested changes, later dismissed
Just the one comment on the deleted file, but otherwise, LGTM

-- Kevin

2024-11-23 23:07 UTC, alexanderl19 commented on apps/backend/.env.sample
Why are we deleting the .env.sample? I think this is unintended.

2024-11-23 23:13 UTC, IsaacNguyen commented on apps/backend/.env.sample
Oh yeah my bad; I didn't realize I did that. I just added it back.

2024-12-10 21:18 UTC, KevinWu098 approved these changes
LGTM!

2024-12-10 21:19 UTC, merged