feat: restyle custom events modal
icssc/AntAlmanac pull request #1062
Opened 2024-12-02 06:10 UTC by xgraceyan

## Summary
Restyled the custom events modal:
- Changed schedule select from checkbox to chip multiple select
  - This is so not all the schedules appear in the main modal (the mass of checkboxes for every schedule is what I'm assuming is mainly contributing to the "ugliness" of the modal)
- Added select variant to Building select props to maintain consistency of outlined style
  - Building select in custom events modal is now outlined variant, while in Maps it is the filled variant
<img width="578" alt="image" src="https://github.com/user-attachments/assets/56b5123b-53c7-49c9-8dc7-d40d2281217c">

It should look better with multiple schedules selected now.
<img width="520" alt="image" src="https://github.com/user-attachments/assets/8a8d7cb0-8c54-4095-ae48-f8ffb67aa5fc">

## Test Plan
Test on different device viewports: Computer (16x9); Tablet (iPad Pro); phone (iPhone 14 pro max); small phone (iPhone SE or any width < 400px)
Test with multiple schedules: 5, 10, 20 schedules selected & make sure the modal doesn't turn ugly.
Test that schedules are selected and the custom event is properly added for all schedules chosen
Test that schedules can be correctly deselected and that they don't have the custom event added to them
Test that the Building selector correctly searches up places in both the custom events modal and Map view, since I made a few changes to it

## Issues

Closes #1025

2024-12-02 06:42 UTC, KevinWu098 requested changes
Comments on two aspects (only based on the SS provided):
1. The day of week buttons being blue on an all-gray modal sticks out to me; could we try using a different variant (secondary should be gray?)
2. The day of week buttons also get unaligned with the rest of the elements on wider modals. Can we style the buttons to take up 100% of horiz. space, by dynamically setting gap or width (I think width makes more sense)?

2024-12-03 00:56 UTC, xgraceyan commented
Gotcha! I've made changes according to your comments:
- As far as I've checked, the secondary theme is white, not gray; I've made the buttons be the default color theme instead, which _is_ gray. However, I think maybe the selector would look better if the buttons selected were the primary blue color, instead of also being gray, as it feels slightly bland right now -- what do you think?
<img width="396" alt="image" src="https://github.com/user-attachments/assets/4138aa0b-dba9-4803-ac49-d0ec448f8f70">

- I've also fixed the alignment of the day select buttons now. They should resize on larger modals and take up all of the horizontal space.
<img width="417" alt="image" src="https://github.com/user-attachments/assets/bc57a256-e33d-4c79-b2bd-5906540556f5">

2024-12-09 02:54 UTC, KevinWu098 commented
The UI tweaks look great -- just updating to say that I'll get around to reviewing this post finals 🫡

2024-12-10 22:23 UTC, KevinWu098 requested changes
Thanks for submitting your first PR! I've added a good handful of (mostly) UI-related tweaks and code quality suggestions.

I promise that I'm not always this pedantic, but it is good to learn (and embrace) our codebase standards early! Let me know if you have any questions 🫡

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                </DialogTitle>
issue: `CustomEventDialog` is used for both creating and editing custom events. This text should reflect the current usage of the dialog

suggestion: check for `props.customEvent` (`boolean`) and swap between Add end Edit.

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                <DialogTitle id="form-dialog-title" style={{ marginBottom: -10 }}>
```suggestion
                <DialogTitle id="form-dialog-title">
```
**edit: the issue+suggestion below are still good practice, but read the comment replying to this one as for why we opt to remove the custom styling altogether**

issue: using marginBottom to override another property (in this case `paddingBottom`) is generally bad practice

suggestion: whenever possible, prefer to identify if you can directly target the style that you would otherwise want to (in this case) "cancel out"

----

nit: Also, when working with MUI v5 (denoted by the import `@mui/material`), use `sx` when styling components

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                <DialogTitle id="form-dialog-title" style={{ marginBottom: -10 }}>
issue: looking at the code below which adds `marginTop` to the element directly below, removing `marginBottom` from `DialogTitle` and `marginTop` from the event name input element achieves the same effect.

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                            style={{ marginTop: 10, width: '100%' }}
```suggestion
```
issue: the styling is unneeded; `width: '100%'` is applied by `fullWidth` on the `FormControl`. See above comments for more details about `marginTop`.

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                    <form noValidate style={{ display: 'flex', gap: 0, marginTop: 10 }}>
```suggestion
                    <FormControl fullWidth sx={{ display: 'flex', flexDirection: 'row', gap: '10px' }}>
```
issue: (I know you didn't add this element) Not sure why we're using an basic `form` element here. Let's replace this with a `FormControl`

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/DaySelector.tsx
> +                marginRight: -5,
```suggestion
                marginTop: 10,
                marginBottom: 10,
                marginLeft: -5,
                marginRight: -5,
```
issue: negative margins (although not always bad) are usually a sign of an antipattern -- they introduce more code to "cancel out" other code. Removing this actually makes the component clearer and more maintanable

suggestion: when adding negative margin, ask yourself where the source of the unwanted spacing is coming from

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/DaySelector.tsx
>          >
```suggestion
                    style={{ gap: '10px' }}
        >
```

suggestion: the answer to the above question (where is this weird spacing on the buttons coming from?) is the margin placed upon each button, which results in spacing on the lefthand and righthand side of the button group. Using `gap` is a more maintainable, cleaner option which only places the spacing between elements

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/DaySelector.tsx
>                      }}
```suggestion
                    onClick={() => handleChange(index)}
```
nit: we can inline this function

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/DaySelector.tsx
>                      }}
```jsx
                    style={{
                        aspectRatio: 1 / 1,
                        width: '40px',
                        minWidth: 'unset',
                    }}
```
Together with applying `gap` to the container, we can simplify the button styles dramatically

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                            style={{ marginRight: 5, marginTop: 10 }}
```suggestion
```
repeat: we can omit these styles using gap

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                            style={{ marginTop: 10 }}
```suggestion
```
repeat: we can omit these styles using gap

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                <DialogActions style={{ padding: '0px 16px 16px' }}>
question: why are we adding padding to the footer/dialog actions? It's not necessarily incorrect, but I think we would prefer to not add arbitrary styles in favor of maintaining styles across components (i.e. other dialogs). 

To be clear, you can (and should) argue for the styling if you have a compelling reason!

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx
> +import { int } from 'aws-sdk/clients/datapipeline';
```suggestion
```
issue: I think you intended to use the `number` type

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx
> +                            {selected.map((value: int) => {
```suggestion
                            {selected.map((value: number) => {
```
repeat: there is no `int` type in TS

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx
> +                    {this.props.scheduleNames.map((name: string, index: int) => {
```suggestion
                    {this.props.scheduleNames.map((name: string, index: number) => {
```
repeat: there is no int type in TS

2024-12-10 22:23 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx
> +                    style={{ marginTop: 2 }}
```suggestion
                    style={{ marginTop: 2 }}
```
nit: i think we can do without the margin top here

2025-01-06 07:01 UTC, xgraceyan commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                <DialogActions style={{ padding: '0px 16px 16px' }}>
This might, and probably is, just be personal preference, but the spacing between the title--the start of the dialog--and the buttons/actions--the end--seems a bit off to me (see image below), and I thought perhaps padding out the actions so the spacing around both corners are consistent might look better. 

However, this seems to be for all MUI dialogs, and I agree it should need to be reflected across all modals if changed, so I've omitted the padding changes in my latest commit (for now, at least). It shouldn't be a huge change regardless and would look fine either way.

![image](https://github.com/user-attachments/assets/5872c991-a965-4bbd-b7b5-bb535c8d9274)

2025-01-06 07:09 UTC, xgraceyan commented
I've committed the requested changes to the best of my knowledge. I'm still familiarizing myself with Typescript, so I totally forgot I had put "int" instead of the actual number type haha. Please let me know if any other edits need to be made, and sorry for the late response--I was out for most of winter break, so I'm just getting around to this now!

2025-01-08 20:42 UTC, KevinWu098 requested changes
Nice work on the previous comments. Have a few more regarding the use of margin, but otherwise, it looks solid!

2025-01-08 20:42 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
>                  <DialogContent>
```suggestion
                <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
```

Similar to how we got rid of `marginLeft` and `marginRight` we should also avoid using margin across our components in favor of using the `gap` styling at the parent container

2025-01-08 20:42 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/CustomEventDialog.tsx
> +                        sx={{ display: 'flex', flexDirection: 'row', gap: '12px', marginTop: '12px' }}
```suggestion
                        sx={{ display: 'flex', flexDirection: 'row', gap: '12px' }}
```
repeat: margin is a bad pattern for maintainability

2025-01-08 20:42 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/DaySelector.tsx
> +                marginBottom: 12,
```suggestion
```
repeat: margin ❌

2025-01-08 20:42 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx
> +            <FormControl style={{ marginTop: '12px', maxWidth: 400 }} fullWidth variant="outlined">
```suggestion
            <FormControl style={{ maxWidth: 400 }} fullWidth variant="outlined">
```

2025-01-10 01:20 UTC, xgraceyan commented
Gotcha, I've replaced all margins now -- thanks for the advice regarding gap styling.

2025-01-10 02:52 UTC, KevinWu098 approved these changes
LGTM

2025-01-10 02:53 UTC, merged