feature/drag-and-drop schedules
icssc/AntAlmanac pull request #1089
Opened 2024-12-29 04:39 UTC by jotalis

![chrome-capture-2024-12-28](https://github.com/user-attachments/assets/1ae67d0e-f241-448c-9931-ba1b1548e782)

## Summary
**Drag-And-Drop**
- Implemented vertically-locked drag-and-drop functionality in the schedule select dropdown, allowing users to reorder schedules
- Added support for desktop, mobile, and also keyboard accessibility (users can also reorder schedules using tabbing and arrow keys)
- Reordering schedules is now treated as an "unsaved" action and cached in local storage. This allows users to retain and reload their unsaved schedule reordering changes even after refreshing the page

**Bug Fixes**
- Resolved an issue where duplicating a schedule that was not currently selected would incorrectly create a new schedule containing the events of the currently selected schedule, instead of duplicating the intended schedule

**Misc**
- Added a disabled cursor for the schedule note text input when in skeleton mode
- Made schedule name tooltip offset consistent with toolbar button tooltip offset

**Note**
Previously, a list of `scheduleNames` was passed down as a prop to the `SelectSchedulePopover` component. For implementing reordering via a sortable dnd list, each `scheduleName` must be mapped to a unique ID because we can't assume all `scheduleNames` are unique yet. 
To address this:
1. A schedule mapping is created, which is really an array of objects where each object contains a scheduleName and its unique id (in this case, its original index in the list).
2. Upon reordering schedules:
   - This local mapping is updated by swapping elements within the array using the schedules' unique IDs
   - The updated schedule order is also reflected in the `AppStore.ts` saved schedule array
   - The currentScheduleIndex in `AppStore` is recalculated accordingly.

**Important**: The local mapping is not **fully** recreated after every reordering action. Instead, only the swapped elements are updated. The local mapping is only recreated during a complete component re-render. If we were to fully recreate the mapping on every reorder, it would disrupt:
- The DND animations / transitions
- The index selector mapping for each toolbar button, causing inconsistencies

## Test Plan
- [ ] Ensure toolbar buttons correctly map to the reordered schedules after swapping
  - Swap around schedules and just ensure that the button popups display the correct text and perform the actions (Copy, Delete, Rename) correctly
- [ ] Ensure schedule swaps are saved as an "unsaved" action and can be reloaded correctly
  - Swap around schedules, reload the page, load unsaved changes and make sure the schedule ordering is the same 
- [ ] Ensure schedule reordering is disabled in skeleton mode
  - Force skeleton mode by [blocking network requests](https://developer.chrome.com/docs/devtools/network-request-blocking) to `https://dev.api.antalmanac.com/trpc/websoc`
- [ ] Ensure schedule swapping works on or via different interfaces (mobile, desktop, tabbing)
- [ ] Ensure styling looks fine for hover tooltips
- [ ] Ensure styling looks fine for skeleton mode schedule note input

## Issues

Closes #1054

2024-12-29 06:50 UTC, MinhxNguyen7 commented
> For implementing reordering via a sortable dnd list, each scheduleName must be mapped to a unique ID because we can't assume all scheduleNames are unique yet.

That is the case now because of the RDS migration. All duplicate schedule names have been mangled.

2025-01-08 20:22 UTC, MinhxNguyen7 submitted a review, later dismissed
Drag icon is not visible in light mode

2025-01-17 22:02 UTC, MinhxNguyen7 commented
@adcockdalton remember to review this. It's marked changes requested because I requested changes, but that has been addressed.

2025-01-22 17:50 UTC, adcockdalton submitted a review, later dismissed
Firstly I must apologize for the incredible delay on reviewing this. It's a useful PR and very well done and written up; it was disrespectful of me to lose track of it.

As for the PR itself, it looks great for the most part, but I had a couple issues. I'll explain how to repro:

1. On reload with unsaved changes, deleted classes are only remembered to have been deleted for what seems to be the "root" schedule. 
- [ ] Add 2-3 schedules
- [ ] Add classes to each
- [ ] Save
- [ ] Delete one class from each (don't save)
- [ ] Reload and check yes to load unsaved changes

You will be redirected to the "root" schedule, for which the class will be deleted (expected behavior in agreement with the main branch). The other schedules will not have their class deleted.

To follow-up with this, it also seems appropriate (if easily implementable from where we are now, since I'd like to merge this in soon) to also remember which schedule was being viewed on reload (without saving). 

2. I couldn't get mobile reordering via touch-scroll to work on my end. This could just be a chrome devtools issue though--is it currently working for you?

--

I also wanted to ask about your reasoning behind the tooltips: 
![image](https://github.com/user-attachments/assets/bcf38b94-2fd4-45a9-8be7-b250c4ae5391)
I'm pretty sure tooltips have to encode additional information in order to be useful for accessibility: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role , but I could be wrong on that--I'm not very familiar with screen readers and the like.

--

LGTM: all other unsaved changes features, tabbing, light mode

2025-01-22 20:25 UTC, jotalis commented
The saving issue seems to be a problem on prod as well. I'll look into why and get it fixed.

The main point of the tooltip is to provide the full length of the schedule name if it exceeds the display limit and is omitted with ellipses. Currently, its behavior renders a tooltip for every schedule name regardless of whether the schedule name length exceeds the display length. This behavior is consistent with prod and can be reworked, if needed, in another PR. This PR just improves the styling of the tooltip offsets.

2025-02-08 10:16 UTC, KevinWu098 requested changes
PR looks really great, thanks for tackling this much-requested feature! Will be a really nice value add for users.

Have added a handful of (mostly) non-blocking / quick fix comments mostly regarding code standards. 

For testing:
- [x] Schedule select popover buttons (duplicate, rename, delete) work after reordering
- [x] Autosave works
- [x] Mobile works, Keyboard controls work
- [x] Skeleton Mode works great (or rather, doesn't)
- [x] Styles look good

- [x] Deleting schedules correctly deletes from the appropriate schedule

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/actions/ActionTypesStore.ts
> +        console.log(unsavedActionsString);
chore: extraneous console log

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/actions/ActionTypesStore.ts
> +            console.log(typeof action);
chore: console log

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
> +                }}
question (non-blocking): why are we applying the cursor styling in both `inputProps` and in `sx`?

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/ScheduleSelect/drag-and-drop/SortableList.tsx
> +            onDragStart={({ active }) => {
suggestion: Generally, it's better to extract logic out into named functions rather than using inline anonymous functions. Won't ask of that in this PR, but I think the codebase would be better off as we move towards explicit handlers

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/ScheduleSelect/drag-and-drop/SortableList.tsx
suggestion: If you followed any documentation / largely drew your implementation from some source(s), it would be beneficial for future maintenance to link it here in a JSDoc

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/ScheduleSelect/drag-and-drop/SortableItem.tsx
> +                style={{
issue: prefer `sx`

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/ScheduleSelect/drag-and-drop/SortableItem.tsx
> +export function DragHandle({ disabled = false }: DragHandleProps) {
question/nit (non-blocking): we should keep files (mostly) atomic -- is there a reason this isn't in another file `DragHandle.tsx`?

2025-02-08 10:16 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/Toolbar/ScheduleSelect/ScheduleSelect.tsx
> +                                        display="flex"
suggestion: place these props in `sx`

2025-02-19 20:25 UTC, jotalis commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
> +                }}
it needs both

2025-02-19 20:33 UTC, KevinWu098 approved these changes
lgtm 🚀

2025-02-21 22:17 UTC, KevinWu098 approved these changes
lgtm -- no way it breaks prod, right? 🙈

2025-02-21 22:18 UTC, merged