Add news component
icssc/AntAlmanac pull request #142
Opened 2021-03-02 10:02 UTC by devsdevsdevs

## Summary
The news section basically lets us put up notifications or messages for our users by simply adding documents to the MongoDB. [An endpoint /api/news has been added to antalmanac-backend ](https://github.com/icssc-projects/antalmanac-backend/commit/f0a59d9246d383cba093a9d13d03a91973d1f466). 

![image](https://user-images.githubusercontent.com/30539874/109630945-5320c000-7afa-11eb-8d2f-d8ffc482caa0.png)

## Test Plan
- Error message when endpoint responds with non 200 code
- Skeleton shows up during load
- Dates are parsed properly
- Too many news items triggers scroll
- Editing DB results in instantaneous changes on frontend

## Issues
#110 

## Future Followup
Implement notification dot when the user has not viewed the latest news item. PR should be merged after this is complete.

2021-03-03 07:09 UTC, ChaseC99 requested changes
Really excited about how easy it will be to create News updates moving forward 😄 📰 

Two small things:
- I left a comment about changing how we handle errors. 
- I think you might need to update the submodule to the latest commit. I had to run `git submodule update --recursive --remote` to get the new endpoint. 

Other than that, this is looking awesome!

2021-03-03 07:09 UTC, ChaseC99 commented on client/src/components/App/News.js
> +                        {'Error loading news items'}
Instead of displaying an error message, **we should just say that there are no new announcements.** 
Makes us look bad if we display an error. Users wouldn't think twice about that if it just says there are no if new updates.

2021-03-03 07:09 UTC, ChaseC99 commented on client/src/components/App/News.js
> +        } else if (this.state.loading === false && this.state.newsItems === null) {
Right now if there are no items in the newsItems array, it displays an empty module. We could handle empty lists the same way as errors (see other comment).
```suggestion
        } else if (this.state.loading === false) {
```

2021-03-03 07:17 UTC, ChaseC99 commented on client/src/components/App/News.js
> +        if (this.state.loading === false && this.state.newsItems !== null) {
```suggestion
        if (this.state.loading === false && this.state.newsItems !== null && this.state.newsItems.length) {
```
Suggestion to fail the check if there are no items in newItems. We don't want to return an empty module.

2021-03-04 04:49 UTC, devsdevsdevs commented
Ready for final review + merge

2021-03-04 16:45 UTC, ChaseC99 approved these changes
Looks fantastic!

2021-03-05 03:10 UTC, merged