Material UI Time Picker
icssc/AntAlmanac pull request #149
Opened 2021-03-19 15:54 UTC by braedons

## Summary
The previous, text entry time picker has been replaced by a material-ui pop-up. AM and PM options are also now supported. The minute hand is restricted to 60-minute increments, but it is still ignored when selecting the time.

![time-picker](https://user-images.githubusercontent.com/25188285/111806094-df6b0b00-888e-11eb-9474-e10d07af113d.gif)

## Test Plan
1. Try searching without specifying start/end times to make sure it functions normally first.
2. Enter a start time, check if results all come after specified time.
3. Enter an end time, check that all results come between the two times.
4. Click on the start time, then click clear, search, then make sure start time is no longer restricted, but that end time still is.
5. Clear end time and make sure classes span the entire day.

## Issues
#135

2021-03-19 18:40 UTC, ChaseC99 requested changes
The code looks good but I'm not sure if this is the right design direction..... 

Personally I think it's less user-friendly to have to click around on a clock. The current implementation of of the time picker seems easier to use and also allows the user to type in their desired time.
![image](https://user-images.githubusercontent.com/29494270/111827182-d84ff700-88a6-11eb-8b31-5e73dd512853.png)

I'm not quite sure what the point of #135 is... maybe @devsdevsdevs could elaborate?

Sorry to be so critical about the design after you've already put in the time to implement this :(

2021-03-20 07:43 UTC, devsdevsdevs commented
> 
> 
> The code looks good but I'm not sure if this is the right design direction.....
> 
> Personally I think it's less user-friendly to have to click around on a clock. The current implementation of of the time picker seems easier to use and also allows the user to type in their desired time.
> ![image](https://user-images.githubusercontent.com/29494270/111827182-d84ff700-88a6-11eb-8b31-5e73dd512853.png)
> 
> I'm not quite sure what the point of #135 is... maybe @devsdevsdevs could elaborate?
> 
> Sorry to be so critical about the design after you've already put in the time to implement this :(

I wanted this change mainly because this experience is not universal. That nice dropdown is native to Chrome and doesn't exist in Firefox.

2021-03-20 15:05 UTC, braedons commented
![image](https://user-images.githubusercontent.com/25188285/111873870-bbbbc980-894f-11eb-8cba-ad672f94e4b0.png)

I could swap the current implementation for a "KeyboardTimePicker", which allows for keyboard input, as well as providing a button for the pop-up.

2021-03-24 18:16 UTC, braedons commented
I've updated it to allow for keyboard input now.

2021-03-25 05:07 UTC, devsdevsdevs approved these changes
Excellent work!

2021-03-26 03:40 UTC, ChaseC99 requested changes
Uh oh looks like the backend submodule got accidentally updated in this PR! Please revert that change before landing :)

In the future, I'd recommend **_against_** using `git add .` or `git add -a`. Instead, we should be adding each file individually. It's annoying but it makes sure we don't accidentally include unwanted changes.

Also I'm still not sure about the clock :/ It's great that it works across different browsers, but if we could find a material-ui dropdown picker, like the current site's, that would be ideal. Maybe we should sync with Design to see what they think?

2021-03-27 02:31 UTC, braedons commented
Ugh, thanks for catching that. I'll keep that in mind next time.
As for the dropdown, if Nathan's cool with it, I'm sure swapping it out would be super easy.

2021-04-01 02:35 UTC, devsdevsdevs commented
> 
> 
> Ugh, thanks for catching that. I'll keep that in mind next time.
> As for the dropdown, if @devsdevsdevs's cool with it, I'm sure swapping it out would be super easy.

Yeah, I'm cool with it

2021-04-13 01:55 UTC, braedons commented
![dropdown_time_picker](https://user-images.githubusercontent.com/25188285/114485101-3929d100-9bc0-11eb-9af0-c18e7e55c96c.gif)

Ok, so I've reverted the previous commit to undo the submodule change. And I've switched from the MaterialUI time-picker to a standard dropdown.

Any comments on the design of it? Would breaking up the hour and the am/pm be better? This is how WebSOC has it.

2021-04-17 08:51 UTC, ChaseC99 requested changes

2021-04-17 08:51 UTC, ChaseC99 commented on client/src/components/SearchForm/AdvancedSearch.js
> +
We can significantly condense this block of code by looping through an array of times and doing some fancy js stuff with `.map`.  
```suggestion
        // List of times from 2:00am-11:00pm
        const menuItemTimes = [
            ...[...Array(10).keys()].map(v => v+2+":00am"), 
            "12:00pm",
            ...[...Array(11).keys()].map(v => v+1+":00pm")
        ]

        // Creates a MenuItem for time selection
        const createdMenuItemTime = (time) => (
            <MenuItem value={`${time}`}>
                {time ? time : <em>None</em>}
            </MenuItem>
        );

        // Build arrays of MenuItem elements for time selection
        const startsAfterMenuItems = ["", "1:00am", ...menuItemTimes].map(time => createdMenuItemTime(time));
        const endsBeforeMenuItems = ["", ...menuItemTimes].map(time => createdMenuItemTime(time));
```

I could be wrong but I don't believe we need a `key` attribute on `MenuItem`.

2021-04-17 08:51 UTC, ChaseC99 commented on client/src/components/SearchForm/AdvancedSearch.js
> +                    }
This is much cleaner than the previous code - great work!

2021-04-17 08:51 UTC, ChaseC99 commented on client/src/components/CoursePane/CourseRenderPane.js
> +                startTime: formData.startTime, //? format(formData.startTime, 'hh:00aaa') : formData.startTime,
Did you mean to include these comments?

2021-04-24 00:26 UTC, braedons commented
Thanks, Chase for holding my hand through this ;). I implemented your improvement for the time generation, but I added a key attribute since it _does_ throw an error/warning otherwise. Everything still seems to work after testing.

2021-04-24 10:38 UTC, ChaseC99 approved these changes
Great work powering through all of the revisions for this PR!! Code looks solid 👌

2021-04-28 01:18 UTC, merged