Main
icssc/AntAlmanac pull request #168
Opened 2021-07-14 05:08 UTC by falsidge

## Summary
Added indexes to map (was retroactively taken out from the repo after the new merge) 
Added routing to map

2021-07-20 08:00 UTC, ChaseC99 commented
We're super stoked about this feature!!

This weekend, I'll have some time to review the code and I'll also pull the analytics on our map usage to verify that these new requests won't push us over the api limit.

Thanks for opening a PR; looking forward to reviewing it!

2021-07-26 08:55 UTC, ChaseC99 requested changes
This is an awesome PR! 

The code to index the map markers is pretty solid. 
The path routing looks great and I can tell a lot of work went into it! The code is brilliant but there's a lot going on there, so it might be a bit hard for future devs to understand. I've left a few comments on how to refactor it so it'll be easier for others to work with in the future.

Let me know if you have questions or need any help. Can't wait to get this out users!

### Requested Changes

- Left additional comments with some recommended changes
- I know in the "Future Followup" you mentioned potentially making the time/distance markers show up on hover. I think you should try to do that in this PR. For routes that are close to each other, the markers cover a lot of the path. 
![image](https://user-images.githubusercontent.com/29494270/126956627-78819574-bef3-431b-9f03-e3912a01131c.png)
- Indexing edge case: when a 2+ classes are in the same building, the index skips over it. 
In this scenario, the student's classes go (1) NS1 -> (2) NS1 -> (3) HSLH. 
The markers should show HSLH as (3) instead of (2).
![image](https://user-images.githubusercontent.com/29494270/126957448-5d5b8258-ef08-4b3c-9274-c96cf6a03e7c.png)
_Side note: Don't worry about indicating that there are two classes in NS1. Seems like it will be tricky, so I'll probably ask our design team for help. I've opened issue #169 to address this in the future. For now, just make sure HSLH is properly labeled (3)_ 



### API Usage
Did some math to anticipate our API usage. We should remain in the free tier! 
> The map tab is viewed about 4,000 times/month.
> There are 5 days in a week and about 2-4 classes per day. 
> So, 4000 * 5 * 3 ≈ 60000 requests/month. 

Since this feature could make our map tab much more popular, we'll continue to monitor the usage to make sure it doesn't go over the 100k limit.

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/stores/AppStore.js
> +        this.setMaxListeners(100);
Please remove

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/stores/AppStore.js
> +                console.log('change current schedule');
Please remove

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                    if (coords) coords += ';';
For clarity
```suggestion
                    if (coords) { coords += ';'; }
```

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                    return;
Nit: you could `.filter` for this

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                const buildingCode = event.bldg.split(' ')[0];
A few buildings have 2 word building codes ("UN CLB", "Student Center", "Mesa Court", "Middle Earth",  "UCI Health",  "Hitachi, PH", "Dean's Office").

It's unlikely that there are classes here, but it's probably better to be safe, especially if new 2-word building codes are added in the future.

```suggestion
                const buildingCode = event.bldg.split(' ').slice(0, -1).join(' ');
```

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                    let waypoint = 0;
- Pull `waypoints` out of `obj`
- Rename `waypoint` to `waypointIndex`
```suggestion
                    let waypoints = obj['waypoints'];
                    let waypointIndex = 0;
```

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                    let latlng = obj['routes'][0]['geometry']['coordinates'];
`latlng` is a little deceiving, since it's actually a list of lats and lngs. 

Rename to `coordinates` and leave a comment explaining that it's a list of latlngs
```suggestion
                    let coordinates = obj['routes'][0]['geometry']['coordinates'];
```

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                    for (let i of latlng) {
Hard to understand what `i` represents at first glance. We can actually destructure here to pull out the lat and lng. The rest of the code in this for loop should be updated accordingly to use lat/lng instead of i[0/1]

```suggestion
                    for (let [lat, lng] of coordinates) {
```
_Notes: this assumes `latlng` is renamed to `coordinates`, per my previous comment_

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                                );
This code is quite difficult to understand because of the response from the API. It'd be hard for other devs to work modify this code in the future.

To make it more readable, we should pull the waypoints and the coordinates out of `obj`, so we no longer reference `obj` again in the code.

Please also add comments, including an explanation what waypoints and coordinates represent.

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +        let colors = [];
Add comments explaining what these vars are for

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                    poly.push(<Polyline color={colors[0]} positions={[path[0][0], coords_array[0]]} dashArray="4" />);
I'm trying to understand what these two positions items represent.

Is this correct?
- coords_array[0] is the pin of the building on the map
- path[0][0] is the start of the route (where solid line begins)
- the line between two points is the dashed line seen below vvvv
![image](https://user-images.githubusercontent.com/29494270/126953052-bc8edeb6-7f6e-4166-9397-87d369a79cd5.png)

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                                        })}
The math here is brilliant, but it's hard to follow inside of the string interpolation.
Pull all the computations out of the string and set them as variables above line 124 (`poly.push(`)

2021-07-26 08:55 UTC, ChaseC99 commented on client/src/components/Map/MapMarkerPopup.js
> +                        </div>
Nit: I think this indentation can come in a bit
```suggestion
                            ${this.props.index}
                        </div>
```

2021-07-26 09:38 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                            if (waypoint != 0) {
```suggestion
                            if (waypoint !== 0) {
```

2021-07-29 06:25 UTC, falsidge commented on client/src/components/Map/UCIMap.js
> +                    poly.push(<Polyline color={colors[0]} positions={[path[0][0], coords_array[0]]} dashArray="4" />);
Yes, this is correct.

2021-07-29 08:17 UTC, ChaseC99 requested changes
Love the hover functionality, this is looking awesome 🔥 

I found a few small bugs and left some suggestions on how to fix them. Once those are resolved I think this is ready to get merged!

- Indexing is off by one. Looks like everything starts at 2 
![image](https://user-images.githubusercontent.com/29494270/127450552-255c92b0-0097-495a-ae16-361cd6803426.png)


- When a day with only one class is selected, the previous route doesn't get cleared
![single_class_bug](https://user-images.githubusercontent.com/29494270/127450339-3874b96e-f686-4295-970e-7e6f678db988.gif)

2021-07-29 08:17 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +import { duration } from '@material-ui/core';
Accidental import, please remove
```suggestion

```

2021-07-29 08:17 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                index++; // index temp fix for courses in same building
Is it actually a "temp" fix? Seems like a solid fix to me
```suggestion
                index++; // always increment index to account for courses within the same building
```

2021-07-29 08:17 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                        index={this.state.day ? (index + 1).toString() : ''}
Since you increment before generating the MapMarkerPopup, we can remove the +1. This should fix the bug where all the classes start at 2
```suggestion
                        index={this.state.day ? index.toString() : ''}
```

2021-07-29 08:17 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +        if (day) {
This fixes the bug where the previous route doesn't get cleared when there's only one class on the map
```suggestion
        // Clear any existing route on the map
        this.setState({ poly: [], info_marker: null });
        
        if (day) {
```

2021-07-29 08:17 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +        }
Per my previous suggestion, if you always clear the route at the top of the function, you no longer need this else statement.
```suggestion
        }
```

2021-07-29 08:17 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                                        <Polyline
Add a `zIndexOffset` here, so the info is displayed in front of the pin
| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/29494270/127456490-7ed56f49-1c71-441b-8466-d7989dffc4a4.png) | ![image](https://user-images.githubusercontent.com/29494270/127456652-8d37798a-3d9c-4e80-bca7-3a446e97505f.png) |

```suggestion
                                        <Polyline
                                            zIndexOffset={100}
```

2021-07-29 10:49 UTC, falsidge commented
Would it be better for the info marker to hover on the mouse?

2021-07-29 14:44 UTC, ChaseC99 commented
> Would it be better for the info marker to hover on the mouse?
Sure I think that would be cool. If you want to try it, go for it!

2021-07-30 02:09 UTC, falsidge commented
> > Would it be better for the info marker to hover on the mouse?
> 
> Sure I think that would be cool. If you want to try it, go for it!

Ok, added.

2021-08-02 02:08 UTC, ChaseC99 approved these changes
Outstanding job on this! Thanks so much for your time developing this feature and responding to feedback. Like I said before, I think users are really going to love this 💯 

I left a few nits but they aren't critical, so feel free to ignore them. I'll merge this PR in on Monday.

ALSO
The ICSSC Projects Committee is planning on launching a Discord this fall for people who want to contribute to projects like AntAlmanac. If you're interested, we'd like to invite you to join early and receive a special "AntAlmanac Contributor" role for this PR.
https://discord.gg/GzF76D7UhY

Thanks again for your hard work 🙌

2021-08-02 02:08 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                            Room: {event.bldg.split(' ').slice(-1)}
Good catch

2021-08-02 02:08 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +    getRoute = (day) => {
Nit: it might make more sense to name this something like `generateRoute`.   
"get" implies that the function is returning data.

2021-08-02 02:08 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                                    function setInfoMarker(event) {
Nit: this function _should_ probably be defined outside of `getRoute`

2021-08-02 07:49 UTC, falsidge commented on client/src/components/Map/UCIMap.js
> +                                    function setInfoMarker(event) {
`this`  gets overrided if put outside. i am not sure how to fix this problem

2021-08-02 08:12 UTC, ChaseC99 commented on client/src/components/Map/UCIMap.js
> +                                    function setInfoMarker(event) {
You could add a parameter to `setInfoMarker` to pass in the `this` object, so you would still be able to reference it.

However like I said, this isn't super critical ¯\_(ツ)_/¯

2021-08-03 03:13 UTC, merged

2021-08-13 00:06 UTC, ChaseC99 commented
These changes have been deployed 🚢