Fix warnings
icssc/AntAlmanac pull request #231
Opened 2022-02-07 08:22 UTC by EricPedley

## Summary
Fixed a bunch of console warnings. After this PR, there shouldn't be any more warnings in the console.
## Test Plan
Click on all the places on the site and ensure that no warnings appear in the console upon doing any action.
## Issues
Closes #199, #163

2022-02-07 08:25 UTC, EricPedley commented
This is a draft because I don't have the .env yet and there are still some errors when I run the frontend locally that I want to confirm will go away once I run the client with the backend.

2022-02-08 09:21 UTC, ChaseC99 requested changes
A lot of great work so far; the console is looking hecka clean.

There are still some errors on the "Added Classes" and "Map" tabs. Could you take a look into these? 
_(loaded class schedule was called `test`)_

![image](https://user-images.githubusercontent.com/29494270/152956160-a33371fa-9e45-4db0-8644-f5bc939ccd18.png)

2022-02-08 09:21 UTC, ChaseC99 commented on client/src/stores/AppStore.js
> +            default: //do nothing
This works for now, but we may want to refactor so that we aren't using multiple stores for AppStore and RightPaneStore

2022-02-08 20:54 UTC, EricPedley commented on client/src/stores/AppStore.js
> +            default: //do nothing
Opened an issue for this

2022-02-09 01:38 UTC, ChaseC99 commented
Still getting a key error for the map, when I click on "Tuesday"
![image](https://user-images.githubusercontent.com/29494270/153104792-eabe9fe5-b640-4863-8992-fc2c6ef47b15.png)

2022-02-09 01:42 UTC, ChaseC99 commented on client/src/components/App/ConditionalWrapper.js
> +});
This is a good abstraction 👍

2022-02-09 01:46 UTC, ChaseC99 commented
I think this is probably where the issue is coming from but I'm not totally sure:
https://github.com/icssc-projects/AntAlmanac/blob/fix-warnings/client/src/components/Map/UCIMap.js#L119

Also important note - @falsidge updated UCIMap.js in #223. So you'll probably need to merge in the latest version of `main`.

2022-02-10 02:01 UTC, ChaseC99 approved these changes
YAY GREAT WORK 🎉  

This PR ended up being wayyyyyy more work than anticipated lol. Great job powering through all of the warnings/errors to clean up our dev environment. While these code changes might not be as glamours as a new feature, it's just as important - if not more - to the longterm success of the project.

Let's 🚢  it

2022-02-10 02:02 UTC, merged