Persist search results
icssc/AntAlmanac pull request #234
Opened 2022-02-12 20:33 UTC by EricPedley

## Summary
After this change, when you switch from the search results tab to added classes or map and back, it keeps the search results up. I also made queryWebsoc cache its results, so doing a search with the same parameters is faster.
## Test Plan
Make some searches, switch to other tabs and back, check that the search results are still up.
## Issues
Closes #124

2022-02-12 20:35 UTC, EricPedley commented
I think a lot of these commits are from me using this branch instead of fix-warnings by accident. Most of the real changes are in the commits with messages "`made queryWebsoc() return json body...`" and "`moved state of RightPane to RightPaneStore`"

2022-02-13 06:39 UTC, ChaseC99 requested changes
Great job on the caching! There's actually no load time when we remove ads. 
![no_ads](https://user-images.githubusercontent.com/29494270/153741916-9e7e1d52-f6d8-4973-b8a3-b9b33473b39f.gif)


Wait for #239 to close, merge in the changes, and we should be good to go!

2022-02-13 06:39 UTC, ChaseC99 commented on client/src/components/CoursePane/CourseRenderPane.js
> +                        courseData: flattenSOCObject(jsonResp),
This will probably be a merge conflict with #239.  
Let's close that one first and then merge the changes into this branch.

2022-02-16 03:42 UTC, ChaseC99 commented
#239 is completed. Resolve the conflicts and you should be good to go! Check in with @kartik-bhagatwala if you have any questions about the ad banner stuff.

2022-02-17 05:07 UTC, ChaseC99 requested changes
Sorry one more edge case that I thought of - when the user presses the back button, we should clear the cache. Otherwise, if they keep searching for the same class the course enrollment numbers won't update.
![image](https://user-images.githubusercontent.com/29494270/154405666-82f1621d-22d4-4231-b3e4-b19bfe42a143.png)

2022-02-17 06:35 UTC, EricPedley commented
The cache is in JS memory, so it gets cleared every time they open the page or refresh. I don't see how having new enrollment data on every search is helpful because I can't think of why you would need the data more accurately than the number when you started your session. Can you elaborate on that use case further?

2022-02-17 09:04 UTC, ChaseC99 commented
> Can you elaborate on that use case further?

### Scenario
Today's the day of your enrollment window. You finished planning your schedule but you leave the site open and keep checking back to see if your classes fill up. Your enrollment window opens up and you go to sign up for classes. `Error: this class is full`. What? AntAlmanac says there are still spots open.

### Explanation
Some classes fill up quick during the enrollment period. It's a really bad user experience if AntAlmanac's numbers and websoc don't match up. We'd lose users' trust. I don't want people to have that thought in the back of their head - "is the data on AntAlmanac reliable?". They shouldn't  feel the need to check WebSoc to verify enrollment numbers. 

Sure they could refresh the page but that's not great ux. Calling the API isn't time expensive, so **each time they search for a class, it should be pulling the latest data from websoc.**

2022-02-18 22:38 UTC, ChaseC99 approved these changes
Great work Eric! This is an awesome feature that is really going to improve the user experience. I can't tell you how many times I've been annoyed having to re-enter my search after switching between tabs.

2022-02-18 22:38 UTC, merged