emove advertisements from course search page
icssc/AntAlmanac pull request #239
Opened 2022-02-12 23:46 UTC by kartik-bhagatwala

## Summary

## Test Plan

## Issues

## Future Followup (Optional)

2022-02-13 06:14 UTC, ChaseC99 requested changes
Dang so quick getting this pr out!

Everything looks solid. Let's just also delete the `AdBanner` component now. We don't want dead code in the project. We can always get it from the git history if we decide to reimplement.

2022-02-13 06:14 UTC, ChaseC99 commented on client/src/components/CoursePane/CourseRenderPane.js
>  import { RANDOM_AD_ENDPOINT } from '../../api/endpoints';
```suggestion

```
Unused import

2022-02-16 00:33 UTC, kartik-bhagatwala commented
Thanks for the input Chase, I've made those changes you suggested.

2022-02-16 03:41 UTC, ChaseC99 approved these changes
LGMT! Great work 🚢

2022-02-16 03:41 UTC, merged