Show delete button on course search page
icssc/AntAlmanac pull request #262
Opened 2022-02-28 00:43 UTC by EricPedley

## Summary
When you add a class from the course search page, the add button is replaced by the color and delete buttons.
![antalmanac deletebutton](https://user-images.githubusercontent.com/48658337/155907151-15b4b42a-bab5-4f1a-8b02-ceef75ec6c0d.gif)
(gif generated with [ScreenToGif](https://www.screentogif.com/); I highly recommend it)
## Test Plan
Actions tested:
- add a class
- delete class from course search
- delete class from calendar
- delete class from added class tab
- change color from course search
- change color from added class tab
- change color from calendar (this doesn't update the color picker immediately in either course search or added classes, but this was a bug beforehand. I'm gonna create a separate issue for that)
- switch tabs, confirm that class stays added or deleted
## Issues
Closes #237 
## Future Followup (Optional)
Identified a new bug, going to create a new issue for that.

2022-03-01 01:07 UTC, ChaseC99 requested changes
This change stacks the icons. Can you get them side-by-side like before?
| Before | After |
| --- | --- |
| <img width="173" alt="image" src="https://user-images.githubusercontent.com/29494270/156085274-79c12c92-63c7-46cb-a74c-67ee30479cdd.png"> | <img width="148" alt="image" src="https://user-images.githubusercontent.com/29494270/156085231-cae62b81-5a5b-42c2-883d-a056ed82a53a.png"> |

2022-03-02 12:41 UTC, ChaseC99 requested changes

2022-03-02 12:41 UTC, ChaseC99 commented on client/src/components/AddedCourses/CustomEventDetailView.js
> +                    return array[4] ? accumulator + 'Sat ' : accumulator + '';
Sorry I don't quite understand what's going on here. 

Why is case 1 and 0 bother `array[0]`? And why are 5 and 6 both `array[4]`?
How does this relate to the color change?

2022-03-02 12:41 UTC, ChaseC99 commented on client/src/components/App/ColorPicker.js
> +            </Fragment>
(see previous comment)
```suggestion
            </>
```

2022-03-02 12:41 UTC, ChaseC99 commented on client/src/components/App/ColorPicker.js
> +            <Fragment>
Nit: use `<>` instead of fragment
This is just a shorthand for React.Fragment (literally does the same thing), but it is more concise and doesn't require an import.
```suggestion
            <>
```

2022-03-02 12:41 UTC, ChaseC99 commented on client/src/components/App/ColorPicker.js
> +import { Fragment } from 'react';
Unneeded import when we use `<>` instead
```suggestion

```

2022-03-02 12:41 UTC, ChaseC99 commented on client/src/components/SectionTable/SectionTableButtons.js
> +export const ScheduleAddCell = withStyles(styles)((props) => {
Good call bringing this to separate file 👍

2022-03-02 12:41 UTC, ChaseC99 commented on client/src/components/SectionTable/SectionTableButtons.js
> +                {<ColorPicker color={color} isCustomEvent={false} sectionCode={sectionCode} term={term} />}
Why is this wrapped in `{}`?

2022-03-03 22:16 UTC, EricPedley commented on client/src/components/AddedCourses/CustomEventDetailView.js
> +                    return array[4] ? accumulator + 'Sat ' : accumulator + '';
It's not related to the color change, it's just a bug I found while testing my changes. And yeah I messed up the array indices 🤦‍♂️.

2022-03-03 22:33 UTC, EricPedley commented on client/src/components/SectionTable/SectionTableButtons.js
> +                {<ColorPicker color={color} isCustomEvent={false} sectionCode={sectionCode} term={term} />}
don't know. removed the curly braces

2022-03-03 22:38 UTC, EricPedley commented on client/src/components/App/ColorPicker.js
> +            <Fragment>
A bunch of other places in our code use Fragment, so I thought we were using it just to be more explicit. Should we open an issue to refactor all instances of Fragment to <>?

2022-03-03 22:46 UTC, ChaseC99 commented on client/src/components/App/ColorPicker.js
> +            <Fragment>
Yes please!

2022-03-03 23:00 UTC, EricPedley commented on client/src/components/App/ColorPicker.js
> +            <Fragment>
ok im on it

2022-03-08 22:19 UTC, ChaseC99 approved these changes
This looks awesome! Once again, great work powering through all of the revisions. 

Sorry for the delay getting this approved, been busy with the end of the quarter 😅

2022-03-08 22:20 UTC, merged