Add refresh button to CourseRenderPane
icssc/AntAlmanac pull request #301
Opened 2022-03-16 00:09 UTC by ChaseC99

## Summary
Adds a refresh button to the Class Search page, so users can reload the latest data from WebSoc.
![refresh](https://user-images.githubusercontent.com/29494270/158492071-b0d822da-6c3f-4440-aecc-7ec85a06027c.gif)

## Test Plan
- Search for a class
- Press the refresh button
    - verify that the component reloads
- Switch to "Added Class" tab and then back to "Class Search"
    - verify that the course data is still cached

## Issues
Close #116

2022-03-16 20:25 UTC, EricPedley requested changes
Changes look mostly good. I feel like having an integer prop passed to CourseRenderPane to force re-render is a bit hack-ish, but probably good enough for now. I think the better way would be making the RightPaneStore emit an event when the cache is cleared, and for CourseRenderPane to listen and re-render itself in that case. I can create an issue for that after we merge these changes.

Since we're adding a refresh button, I think we should not clear the cache automatically when you go back to the search menu and do a different search. We just need to remove lines 3 and 58 from `RightPaneStore.js`. It makes the experience much nicer when you have to search a department again and it just loads instantly, plus I think people constantly looking for enrollment updates would be using the new refresh button instead of repeatedly doing the same search.

2022-03-25 18:09 UTC, ChaseC99 commented
Hmm I still think we run into the same issue though... someone leaves a tab open overnight, comes back to search in the morning, and gets results that are different from WebSOC.

I would be open to caching if we also included a time limit on it. Maybe we add a time field in the cache so if a cached result is older than 30min, we ignore it and fetch from WebSOC again.

We can create a separate issue for this if you'd like to work on it!

2022-03-26 04:19 UTC, EricPedley commented
> Hmm I still think we run into the same issue though... someone leaves a tab open overnight, comes back to search in the morning, and gets results that are different from WebSOC.
> 
> I would be open to caching if we also included a time limit on it. Maybe we add a time field in the cache so if a cached result is older than 30min, we ignore it and fetch from WebSOC again.
> 
> We can create a separate issue for this if you'd like to work on it!

Yeah this makes a lot of sense. I'll make the issue.

2022-03-26 04:22 UTC, EricPedley approved these changes

2022-03-26 04:24 UTC, merged