Changed 'cancel' and 'load' button to white in the save/load option a…
icssc/AntAlmanac pull request #322
Opened 2022-03-30 07:32 UTC by yialan6

## Summary
Changed 'load' and 'cancel' button to white and made back and back button more visible by changing color to black and removing transparency.
## Test Plan
Checked changes on localhost
## Issues

## Future Followup (Optional)
<img width="944" alt="Screen Shot 2022-03-30 at 12 26 18 AM" src="https://user-images.githubusercontent.com/65580950/160776357-a54f0661-9016-42cd-8045-96f465d9a070.png">
<img width="644" alt="Screen Shot 2022-03-30 at 12 25 48 AM" src="https://user-images.githubusercontent.com/65580950/160776364-8771279d-8366-4bdd-a6b5-3fbed6a06f75.png">
<img width="1087" alt="Screen Shot 2022-03-30 at 12 26 28 AM" src="https://user-images.githubusercontent.com/65580950/160776338-acaa1ab6-4166-48c3-9a41-a2e4f84e3df6.png">

2022-03-30 19:12 UTC, ChaseC99 commented
Could you include some screenshots for how this looks in light mode?

2022-03-30 22:23 UTC, yialan6 commented
Here you go!
<img width="1127" alt="Screen Shot 2022-03-30 at 3 21 31 PM" src="https://user-images.githubusercontent.com/65580950/160940937-7d7a714d-5352-4fd3-9a84-1a595a25b3e0.png">
<img width="920" alt="Screen Shot 2022-03-30 at 3 21 15 PM" src="https://user-images.githubusercontent.com/65580950/160940947-9a0a6590-e002-407d-a385-6e53cef1854c.png">

2022-04-01 07:14 UTC, ChaseC99 requested changes
Looking solid! Just a few small changes and it should be good to go

2022-04-01 07:14 UTC, ChaseC99 commented on src/components/CoursePane/CoursePaneButtonRow.js
> +import { withThemeCreator } from '@material-ui/styles';
Remove unused import.
```suggestion
```

2022-04-01 07:14 UTC, ChaseC99 commented on src/components/App/LoadSaveFunctionality.js
> +                        <Button onClick={() => this.handleClose(false)} color="white">
I'd like to keep these as `primary` when in light mode. You can conditionally determine this using the  `isDarkMode` helper function: `import { isDarkMode } from '../../helpers';`

2022-04-01 07:14 UTC, ChaseC99 commented on src/components/App/LoadSaveFunctionality.js
> +                        <Button onClick={() => this.handleClose(false)} color="white">
Example (idk if this actually works)
```suggestion
                        <Button onClick={() => this.handleClose(false)} color={isDarkMode ? "white" : "primary"}>
```

2022-04-02 04:24 UTC, yialan6 commented
<img width="706" alt="Screen Shot 2022-04-01 at 9 23 00 PM" src="https://user-images.githubusercontent.com/65580950/161366160-c9e398b1-0dab-4945-b2df-ad23ec0c09ab.png">
<img width="640" alt="Screen Shot 2022-04-01 at 9 22 52 PM" src="https://user-images.githubusercontent.com/65580950/161366161-4529146e-1777-4c5d-a23c-ba8ea84709b8.png">
Here are screenshots of the changes!

2022-04-02 07:16 UTC, ChaseC99 approved these changes
Looks awesome, great work! I'll get this deployed right now :D

2022-04-02 07:16 UTC, merged