Rename and delete schedules
icssc/AntAlmanac pull request #368
Opened 2022-05-01 18:41 UTC by Douglas-Hong

## Summary
- There is a menu on the left of the calendar toolbar to edit your schedule. Inside the menu, you can rename or delete your current schedule.
- To add a schedule, you now have to go to the select menu with all your schedule names and then click the last menu item.

## Test Plan
- If a user renames a schedule, its name is changed in all appropriate places, such as the custom events dialog, the select menu that shows schedule names, and the right pane.
- After a user deletes a schedule, all schedules after the deleted schedule should be shifted back. Make sure the courses, custom events, and finals are correct for each schedule after the deletion occurs.
- If a user deletes a schedule, the current schedule should now be the schedule that was after the deleted schedule; if the user deletes their last schedule, the current schedule should be the schedule that was before the deleted schedule.
- If a user only has one schedule, the "Delete Schedules" button should be disabled.

Demo:

https://user-images.githubusercontent.com/78244965/166159887-21fe6bfc-219a-4ee6-af9f-cb934d308191.mp4

## Issues
- Closes #331

2022-05-04 23:17 UTC, ChaseC99 commented
Thoughts on adding an "Add" icon to the "Add Schedule" option? I think it would help it stand out a little more.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/29494270/166840250-2c898546-ceae-413b-9003-c35182ee7ab7.png">

Any of these might look good.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/29494270/166840332-37d1217c-a870-4388-9664-ee0b2b7b9db0.png">

2022-05-05 02:02 UTC, ChaseC99 requested changes
Functionality looks awesome! A few code clean ups and it should be good to go.

2022-05-05 02:02 UTC, ChaseC99 commented on src/components/Calendar/DeleteScheduleDialog.js
> +                    </DialogContentText>
Can we put "You cannot undo this action." on a new line?

2022-05-05 02:02 UTC, ChaseC99 commented on src/components/Calendar/EditSchedule.js
> +    const [anchorEl, setAnchorEl] = useState(null);
Deference classes from props up here so that later on, you can just do `classes.<style>` instead of `props.classes.<style> over and over again.
```suggestion
const EditSchedule = (props) => {
    const { classes } = props;

    const [anchorEl, setAnchorEl] = useState(null);
```

2022-05-05 02:02 UTC, ChaseC99 commented on src/components/Calendar/EditSchedule.js
> +                <ScheduleNameDialog
Good work reusing the ScheduleNameDialog component here 👍

2022-05-05 02:02 UTC, ChaseC99 commented on src/actions/AppStoreActions.js
> +};
Wow adjusting all the indexes seems like a pain.... Once we move to new schema, we can remove this right?

2022-05-05 02:02 UTC, ChaseC99 commented on src/actions/AppStoreActions.js
> +};
Also - good comment explaining what's going on here 👍

2022-05-05 02:02 UTC, ChaseC99 commented on src/components/Calendar/CalendarPaneToolbar.js
> +    const [openSchedules, setOpenSchedules] = React.useState(false);
Nit: we should just import useState at the top
```jsx
import React, { useState } from 'react';
```

So that this will simply become:
```suggestion
    const [anchorEl, setAnchorEl] = useState(null);
    const [openSchedules, setOpenSchedules] = useState(false);
```

2022-05-05 02:02 UTC, ChaseC99 commented on src/components/Calendar/CalendarPaneToolbar.js
> +            <EditSchedule scheduleNames={props.scheduleNames} scheduleIndex={props.currentScheduleIndex} />
Deference these from props at the top of the function.

```jsx
const { classes, scheduleNames, currentScheduleIndex } = props;
```

```suggestion
            <EditSchedule scheduleNames={scheduleNames} scheduleIndex={currentScheduleIndex} />
```

2022-05-05 02:02 UTC, ChaseC99 commented on src/components/Calendar/ScheduleNameDialog.js
> +const ScheduleNameDialog = (props) => {
Let's also de-structure here too
```suggestion
const ScheduleNameDialog = (props) => {
    const { onOpen, onClose, scheduleIndex, scheduleNames, rename } = props; // there's probably more 
```

2022-05-05 05:03 UTC, Douglas-Hong commented on src/actions/AppStoreActions.js
> +};
Yes, once we move to the new schema, we don't need this function anymore! In the new schema, each schedule is independent, so deleting a schedule will not affect the courses or custom events of other schedules.

2022-05-05 06:42 UTC, ChaseC99 approved these changes
LGTM 🎉

2022-05-06 22:25 UTC, merged