Added getDefaultTerm function to termData
icssc/AntAlmanac pull request #397
Opened 2022-06-10 21:44 UTC by felixweiguangwu

## Summary
Added getDefaultTerm function to termData.
Updated the imports of termData with the addition of getDefaultTerm.
Changed the usage of termData[defaultTerm] to getDefaultTerm().

## Test Plan
The function getDefaultTerm printed correct result in the console.
![Screenshot 2022-06-10 143000](https://user-images.githubusercontent.com/73359978/173155017-c542d38f-8837-4843-9671-1a7824be77c8.png)

## Issues
Closes #382

## Future Followup  
Might need change to the way termData is accessed so that defaultTerm is not longer accessible outside of termData.

2022-06-11 01:33 UTC, ChaseC99 commented
> ### Future Followup
> Might need change to the way termData is accessed so that defaultTerm is not longer accessible outside of termData.

Eh that's probably fine for `defaultTerm` to still be accessible. 

I'll review this more later this weekend!

2022-06-11 01:38 UTC, ChaseC99 requested changes
Looking solid! Just remove some unused imports and it should be good to go.

2022-06-11 01:38 UTC, ChaseC99 commented on src/components/SectionTable/SectionTableBody.js
> +import { defaultTerm, termData, getDefaultTerm } from '../../termData';
```suggestion
import { getDefaultTerm } from '../../termData';
```

Unused import

2022-06-11 01:38 UTC, ChaseC99 commented on src/stores/RightPaneStore.js
> +import { termData, defaultTerm, getDefaultTerm } from '../termData';
```suggestion
import { getDefaultTerm } from '../termData';
```

Unused import

2022-06-11 01:38 UTC, ChaseC99 commented on src/components/EnrollmentGraph/GraphModalContent.js
> +import { termData, defaultTerm, getDefaultTerm } from '../../termData';
```suggestion
import { termData, defaultTerm } from '../../termData';
```

Unused import

2022-06-11 04:35 UTC, ecxyzzy approved these changes
Looks good to me—all of the changes have been addressed. Great work!

Just going to re-request a review from Chase so we can merge this.

2022-06-13 20:36 UTC, ChaseC99 approved these changes

2022-06-13 20:36 UTC, merged