Fix Github Actions not checking status properly
icssc/AntAlmanac pull request #447
Opened 2022-11-15 07:55 UTC by Voark

## Summary

## Test Plan

## Issues
Closes #

2022-11-22 02:03 UTC, EricPedley requested changes
Is there any way we can encapsulate these steps so we don't have to have the code duplicated between these two workflows? Or if we can't just add a comment or note or something that indicates the code is in two places if anyone in the future needs to update it

2022-11-22 08:36 UTC, Voark commented
> Is there any way we can encapsulate these steps so we don't have to have the code duplicated between these two workflows? Or if we can't just add a comment or note or something that indicates the code is in two places if anyone in the future needs to update it

There is a way with reusable workflows, I didn't do it before because the environments aren't shared between the normal workflow and the reusable one. However looking at it now I don't remember exactly why I didn't do it... Will try and see what happens.

2022-11-28 04:20 UTC, EricPedley commented
What does "stabilize stack" mean?

2022-11-28 04:21 UTC, Voark commented
> What does "stabilize stack" mean?

Wait for the stack status to stabilize, i.e. finish anything in progress.

2022-11-28 04:21 UTC, EricPedley approved these changes

2022-11-28 04:22 UTC, merged

2022-11-28 04:23 UTC, EricPedley commented
Actually maybe we should add that to the description of the action

2022-11-28 04:24 UTC, EricPedley commented
I'll open another PR for it