Dark Mode Screenshots Bug
icssc/AntAlmanac pull request #461
Opened 2023-01-16 08:58 UTC by JacE070

## Current Progress
Working:
- Setting the font color to match the theme.

Done:
- Setting the background color to match the theme.

![image](https://user-images.githubusercontent.com/53324036/212637849-e7df896f-ccbd-486c-bfb5-5c6fcc12db05.png)

## Issues
Closes https://github.com/icssc/AntAlmanac/issues/442

2023-01-19 18:55 UTC, EricPedley requested changes
Can you fix the TODO item you added where the screenshot defaults to `light` if the theme is set to auto? It seems like it wouldn't be too hard but if you think it would be a big enough change to warrant its own issue and/or PR let me know *why*.

2023-01-19 18:55 UTC, EricPedley commented on src/components/Calendar/ScheduleCalendar.js
> -        if (isDarkMode()) {
Why did you replace this call to `getDarkMode`? If it isn't working, I think it's worth modifying `isDarkMode` itself so that it can work here.

2023-01-19 18:55 UTC, EricPedley commented on src/components/Calendar/ScreenshotButton.js
> -            backgroundColor: window.localStorage.getItem('theme') === 'light' ? '#fafafa' : '#303030',
Why aren't you using `isDarkMode` here?

2023-01-20 02:14 UTC, JacE070 commented
> Can you fix the TODO item you added where the screenshot defaults to `light` if the theme is set to auto? It seems like it wouldn't be too hard but if you think it would be a big enough change to warrant its own issue and/or PR let me know _why_.

2023-01-20 02:15 UTC, JacE070 commented
> > Can you fix the TODO item you added where the screenshot defaults to `light` if the theme is set to auto? It seems like it wouldn't be too hard but if you think it would be a big enough change to warrant its own issue and/or PR let me know _why_.

I solved it when I took a look to isDarkMode() again LOL. Thanks for pointing it out!

2023-01-28 08:01 UTC, JacE070 commented
Re-open PR in TypeScript

2023-01-28 08:01 UTC, closed without merging