Fix techdebt theme
icssc/AntAlmanac pull request #477
Opened 2023-02-07 05:50 UTC by bevm0

## Summary

## Test Plan

## Issues

Closes #

2023-02-08 04:14 UTC, EricPedley requested changes
Code looks mostly fine with a few comments. Besides those, here's some other things I'd like fixed:
- The favicon doesn't show up
- The font is different
- A lot of the components got bright white borders with these changes, and I think they looked better before
- In the search results page, the copy schedule and clear schedule buttons look different
- The different tabs (search, added classes, map) get blue text color when they're selected.
- The course info button on the search results is blue when it was previously light grey
- The class statuses don't have color anymore
- In the maps tab, if you click on a pin, the contrast on the "directions" button is pretty bad
- The "Add Custom" popup elements overlap each other
Whenever I say something is different here, the implication is that I think it should look like it did originally. There are some style changes that I thought looked better like the new icon for import study list that you should keep, but for everything else can you either fix them or let me know why that change should stay when we merge this?

After resolving those we can merge this one and #470.

2023-02-08 04:14 UTC, EricPedley commented on index.html
> +        <link rel="stylesheet" href="/google_font_roboto_300_400_500_700.css" />
Just noticed it on this PR, but why is index.html in the root directory instead of in `public` now? Also, why does the font look different on the preview deployment?

2023-02-08 04:14 UTC, EricPedley commented on src/components/App.tsx
> +                ...(this.state.darkMode
Can we simplify this by just putting the ternary as the value of `pallette` instead of doing this destructuring, since the other properties are commented out? Also, if we're not going to use those commented-out values I think we should just delete them.

2023-02-08 04:14 UTC, EricPedley commented on src/components/AppBar/ImportStudyList.tsx
> +import { ContentPasteGo } from '@mui/icons-material';
Good change 👍

2023-02-08 04:14 UTC, EricPedley commented on src/components/AppBar/ImportStudyList.tsx
>      render() {
Can you get this component to look more like it did originally?
Original:
![image](https://user-images.githubusercontent.com/48658337/217429824-00fbd1e0-2007-4c8a-a608-9be6676167a6.png)

Yours:
![image](https://user-images.githubusercontent.com/48658337/217429753-6a619ccc-f1fa-40b9-8cd9-c8befe0daf48.png)

2023-02-13 19:49 UTC, bevm0 commented
Good demo of what the project looks like in mui5; gonna work on function components first

2023-02-13 19:49 UTC, closed without merging