Add schedule notes [Draft]
icssc/AntAlmanac pull request #483
Opened 2023-02-12 05:37 UTC by Douglas-Hong

## Summary
- Users can add a note for each of their schedules. They can also edit, save, and load their notes.
- Schedule notes will be displayed under the search bar.

Task list:
- [x] Allow user to write/edit a note while they create or edit a schedule.
- [x] Add a box under the search bar that displays the current schedule's notes.
- [ ] Allow schedule notes to be saved and loaded (waiting for schedule structure rewrite). For old schedules, make sure each schedule's note is just an empty string.
- [ ] Add a way to edit a schedule note by clicking somewhere in the note box.

## Test Plan
- For a schedule with no notes, make sure the note box displays a message that says there is no note.
- Create a new schedule with notes. Make sure the note is displayed properly in the box.
- Edit a schedule that already has a note, and make sure the note box changes.
- Create multiple schedules with notes. Switch between these schedules and make sure the displayed notes are correct.
- When you delete a schedule, make sure the notes are still displayed correctly for the remaining schedules.
- Test various notes. Make sure newlines are processes and the max character limit is enforced.

## Issues

Closes #413

2023-03-01 02:08 UTC, Voark requested changes
Overall code that you have written seems good to me, but there are a few issues related to undoing and schedule notes. When editing the schedule through the edit schedule button, we add an undo state so the schedule note change their can be undone. However it cannot be undone when updating from the note container because you didn't add an undo state save in `Schedules.ts`. I think this is probably the intended behavior (undo button does not undo schedule note change) but because of how we save schedules the undo button will undo it anyways. To fix this I think we need to add some more complicated undo saving/loading where we save/load all the properties except the notes. @EricPedley what are your opinions overall on undo state tracking for schedule notes?

On a slightly related note I think it would also be OK to remove the ability to edit schedule note from the edit schedule button because of the extra complexity of handling undoes (we still display the note in the pop up just not editable). 

Also small feature request: a "Clear Schedule Notes" button or trash can in the notes area in added classes.

2023-03-01 02:08 UTC, Voark commented on src/actions/AppStoreActions.ts
> +export const editSchedule = (scheduleName: string, scheduleIndex: number, scheduleNote: string) => {
nit: I feel like `scheduleIndex` should be last

2023-03-01 02:08 UTC, Voark commented on src/stores/Schedules.ts
> +    editSchedule(newScheduleName: string, scheduleIndex: number, newScheduleNote: string) {
Nit: same `scheduleIndex` thing as before

2023-03-07 02:29 UTC, Douglas-Hong commented
From standup:
- If the schedule note was edited through a modal, then maybe we can do undo schedule notes.
- If the schedule note was edited through the box itself, it should not be undone.
- Clear button shouldn't be necessary since the user can just highlight all the text and delete it.

2023-03-30 02:23 UTC, Voark reviewed
Code changes look good to me, only change I think might help is just using a random number generator instead of a counter every time you add a new schedule so you don't need to keep track and increment the class variable.

Waiting on merge conflict resolution so the changes will be deployed to approve.

2023-04-01 06:07 UTC, Voark approved these changes
LGTM!!

2023-04-01 17:40 UTC, merged