Assign random reviewer to PR
icssc/AntAlmanac pull request #550
Opened 2023-04-17 18:01 UTC by Voark

## Summary
Assigns a random reviewer from `.github/reviewer-lottery.yaml` to the PR when it is marked as ready to review.

## Test Plan

## Issues

Closes #

2023-04-17 18:56 UTC, Voark commented
Least messy actions PR history

2023-04-18 23:04 UTC, EricPedley requested changes

2023-04-18 23:04 UTC, EricPedley commented on .github/reviewer-lottery.yml
> +    usernames:
You forgot to add @JacE070

2023-04-20 08:27 UTC, Voark commented on .github/reviewer-lottery.yml
> +    usernames:
Done

2023-04-24 19:30 UTC, EricPedley approved these changes
🚀

2023-04-24 19:30 UTC, merged