Adjusted color hue algorithm for the same sectionType
icssc/AntAlmanac pull request #574
Opened 2023-05-16 02:25 UTC by KevinWu098

## Summary
Noticed previously that the "nuclear" use case of selecting all available courses of a particular course title (ie every single ICS 32A discussion course) resulted in overuse of the hue, resulting in: Pink -> Light Pink -> ... -> White -> Black

<img width="1445" alt="Issue Screenshot" src="https://github.com/icssc/AntAlmanac/assets/100006999/fb387bbb-68fd-466f-84c4-b4611ce1e3d6">

## Test Plan
- Confirmed that when selecting new courses, the same sectionType (ie ICS 32A LAB) would maintain the same color. 
- This would not affect future selections of other sectionTypes, like ICS 32A LEC
- When there are 3 types (DIS, LEC, LAB), functionality is as intended

## Issues
- Doesn't necessarily interfere with my PR, but for classes like STATS 67, multiple lectures and associated DIS create a similar issue, but this seems less critical since they ARE different courses

<img width="1445" alt="Potential Edge Case" src="https://github.com/icssc/AntAlmanac/assets/100006999/82dff3d1-6d82-40c7-b9e4-e73b5858b827">

2023-05-19 17:45 UTC, MinhxNguyen7 requested changes, later dismissed
Makes sense. Just a few changes

2023-05-19 17:45 UTC, MinhxNguyen7 commented on apps/antalmanac/src/stores/Schedules.ts
> +    //If the same courseTitle exists, but not the same sectionType, return a hue
```suggestion
    //If the same courseTitle exists, but not the same sectionType, return a close color
```

It's the same hue and saturation with a different lightness (currently). I prefer not to say that the function returns a hue of the original color, which would imply that it's a different hue.

2023-05-19 17:45 UTC, MinhxNguyen7 commented on apps/antalmanac/src/stores/Schedules.ts
> +    const existingSectionsType = existingSections.filter((course) => course.section.sectionType === newSection.section.sectionType)
I would combine this with the other filtering that `existingSections` does. There's not really a reason to do two passes

2023-05-19 18:12 UTC, KevinWu098 commented on apps/antalmanac/src/stores/Schedules.ts
> +    const existingSectionsType = existingSections.filter((course) => course.section.sectionType === newSection.section.sectionType)
I created a second filtering because otherwise I'm not sure how I would be able to distinguish between courseTitle versus sectionType.

Cases:
1. courseTitle && sectionType => Same Color
2. courseTitle => Close Color
3. nothing => New Color

If I don't have two arrays, one which checks for courseTitle and one for sectionType, I'm not sure I would be able to fulfill case 1 AND 2.

2023-05-21 03:01 UTC, MinhxNguyen7 approved these changes
Tested and LGTM!

2023-05-21 03:01 UTC, merged