Escape Dialog
icssc/AntAlmanac pull request #579
Opened 2023-05-17 22:21 UTC by KevinWu098

## Summary
*Initially PRed in #578 but I did a dumb, so I made a new branch 😅
Adding in the capability to use the escape key and/or click out of the Dialogs in the AppBar & the Add Custom Event dialog. 

![Escape Dialog Responsiveness](https://github.com/icssc/AntAlmanac/assets/100006999/811dfb60-d36a-46a0-9ca6-2b4c99298ac9)

## Test Plan
- Tested `AppBar`'s Save, Load, Import, and About dialogs for responsiveness on Esc and clicks outside.
- Also tested the Add Custom event button for the same

## Issues
For the Import Dialog, the onClose function also creates a Snackbar error when hitting escape/clicking out. To solve that, I created another function `handleEscClose` since I couldn't figure out how to differentiate between clicking import with an empty Study List input field.

in `AboutPage.tsx` I added in the handleClose function, which also required the enterEvent function. Honestly, it looks kinda nasty to me, so would appreciate feedback on how to handle `handleClose` since it seems to need `this.enterEvent`.

I have no doubt there's some React jargon that describes this solution of mine as not best practice 😵‍💫

## Future Followup
Currently keeping this as a draft so that I can further investigate if Calendar event popups 

Closes #551

2023-05-18 21:28 UTC, KevinWu098 commented
Currently, still working on the escape Dialog for the schedule selector in the top right, but the rest should be good for review :) 💖

2023-05-20 04:55 UTC, MinhxNguyen7 requested changes
Mostly LGTM!

I would say that the rename should recover the schedule's name. I think that should be pretty straightforward, and that would, at the very least, match the behavior of the other inputs. I also think that that makes the most sense, regardless.

Also, I would like you to reformat the PR description so that it's easier to skim, though. The idea is that someone can come back in the future to see why you made the changes in this PR.

The summary should be a summary of the changes that you made. There are some in the issues section that you crossed out because you resolved them. 

If you'd like to keep the writing, I'd add an additional notes section at the bottom. In any case, I think the `Issues` section is to reference issues in the repository that this PR addresses. It's not to document the issues you had writing it.

The same idea applies to the `Future Folloup` section. If it's been done, it wouldn't be a _future_ follow-up.

2023-05-20 06:21 UTC, KevinWu098 commented
> Mostly LGTM!
> 
> I would say that the rename should recover the schedule's name. I think that should be pretty straightforward, and that would, at the very least, match the behavior of the other inputs. I also think that that makes the most sense, regardless.
> 
> Also, I would like you to reformat the PR description so that it's easier to skim, though. The idea is that someone can come back in the future to see why you made the changes in this PR.
> 
> The summary should be a summary of the changes that you made. There are some in the issues section that you crossed out because you resolved them.
> 
> If you'd like to keep the writing, I'd add an additional notes section at the bottom. In any case, I think the `Issues` section is to reference issues in the repository that this PR addresses. It's not to document the issues you had writing it.
> 
> The same idea applies to the `Future Folloup` section. If it's been done, it wouldn't be a _future_ follow-up.

Aye Aye cap'n! PR has been trimmed down and I left the rename functionality as is!

2023-05-21 02:39 UTC, MinhxNguyen7 approved these changes
👍

2023-05-21 02:43 UTC, merged