Functionality: Escape now escapes Calendar event popups
icssc/AntAlmanac pull request #580
Opened 2023-05-18 04:30 UTC by KevinWu098

## Summary
Follows up from #579 which resulted from #551 

_Because I'm very shaky on React Hooks, I made a new branch with just the changes to `CourseCalendarEvent.tsx` for review and feedback specifically on this, since it isn't a Dialog & `onClick`!_

- Previously, you had to click out of Calendar Event popups (which may cover other events). 
- Implemented React Hooks that listens for the "escape" keyCode and sets the visibility of the `Paper` popup to `'none'`.

![Escape Functionality](https://github.com/icssc/AntAlmanac/assets/100006999/9c87dbc6-0322-4c8a-a817-87ba615d8e2f)

## Test Plan
Checked that on "escape", the Paper/popup disappears.

2023-05-18 22:57 UTC, MinhxNguyen7 reviewed
LGTM and works. I think that this is the idiomatic way of implementing an event listener.

I would just nitpick and say that `event.keyCode === 27` should be documented, either with a comment or with `const escapeKeyCode = 27`...

2023-05-19 02:01 UTC, KevinWu098 commented
> LGTM and works. I think that this is the idiomatic way of implementing an event listener.
> 
> I would just nitpick and say that `event.keyCode === 27` should be documented, either with a comment or with `const escapeKeyCode = 27`...

Added in the documentation w/ a comment!

2023-05-20 05:25 UTC, MinhxNguyen7 requested changes
I should've said this last time, but I would rename `isShown` to something like `paperRef`. It's not a bool.. After that, I think it's ready to merge. Sorry about that

2023-05-20 06:14 UTC, KevinWu098 commented
> I should've said this last time, but I would rename `isShown` to something like `paperRef`. It's not a bool. After that, I think it's ready to merge. Sorry about that

Done! 💖

2023-05-21 02:51 UTC, MinhxNguyen7 approved these changes
Tested and LGTM!

2023-05-21 02:59 UTC, merged