Codebase cleanup
icssc/AntAlmanac pull request #612
Opened 2023-06-05 00:47 UTC by KevinWu098

## Summary
`npm run lint` & `npm run format` were run in `apps/antalmanac`. _🙅‍♂️ tech debt_

## Test Plan
Everything's still clean, changes are mostly minor / syntactical.

## Issues
Closes #610 

## Additional Notes
In commit 3541628de98d65d48403d334e75755899b051c3c, I had to chuck in an `eslint-disable-next-line` to allow for `@ts-ignore` which allowed an escape key listener/function to work. If that's an issue, LMK!

2023-06-09 05:18 UTC, MinhxNguyen7 requested changes
Looks good except for the one comment. I'll have to check that the page actually works the next time around.

2023-06-09 05:18 UTC, MinhxNguyen7 commented on apps/antalmanac/src/components/AppBar/ImportStudyList.tsx
> +                    }
Regardless of what the linter says, I think that this is just less readable. @EricPedley, what do you say should take precedent?

2023-06-09 05:18 UTC, MinhxNguyen7 commented on apps/antalmanac/src/components/Calendar/CourseCalendarEvent.tsx
> +                if (paperRef.current) paperRef.current.style.display = 'none';
This should just be one condition. Never nest (if you don't have to)

2023-06-09 05:18 UTC, MinhxNguyen7 commented on apps/antalmanac/src/components/RightPane/Map/MapMarker.tsx
>              markerRef.current.leafletElement.closePopup();
This is cursed, but it's being re-written anyway, so it doesn't matter

2023-08-15 05:31 UTC, ap0nia commented
The codebase has changed a good amount since this was opened. I'm gonna close this; you can open another PR if you'd like.

2023-08-15 05:31 UTC, closed without merging