[WIP] Create AddedCourseButtonRow
icssc/AntAlmanac pull request #665
Opened 2023-08-21 11:20 UTC by KevinWu098

## Summary
1. Show/Hide Column button is now also accessible on the Added Course Pane, fixing the user-flow issue referenced in the original pull request

2. Copy Schedule and Clear Schedule have been moved into IconButton components alongside the new Show/Hide column button. This maintains visual consistency with three "action" buttons at all time. More specifically, it also allows the Show/Hide button to maintain the same position on the screen.

## Test Plan

## Issues

Closes #

2023-08-22 03:51 UTC, KevinWu098 commented
Gonna put this PR on hold until I figure out what icon / visual language works best for users over in #659

2023-09-01 09:52 UTC, KevinWu098 commented
> Gonna put this PR on hold until I figure out what icon / visual language works best for users over in #659

This PR is unblocked now since we decided on the Clear icon for deleting schedules

2023-09-01 16:00 UTC, MinhxNguyen7 requested changes
Everything looks good functionality-wise. Code-wise, nothing is amiss, but could you extract the three buttons as their components while you're working on this? There's too much code there.

2023-09-01 20:28 UTC, KevinWu098 commented
Leaving this as a draft until #659 goes through

2023-09-04 05:18 UTC, KevinWu098 commented
Closing this PR since `Added Course Pane` will be rewritten in #569

2023-09-04 05:18 UTC, KevinWu098 commented
Closing this PR since `Added Course Pane` will be rewritten in #569

2023-09-04 05:18 UTC, closed without merging