Convert button to Chip component
icssc/AntAlmanac pull request #668
Opened 2023-08-22 10:07 UTC by KevinWu098

## Summary
1. Change button component to Chip component in Calendar Event popup.
2. Makes the "Copy Button" (or Chip, I suppose) consistent across both the Calendar popup and the Right Pane.

<img width="522" alt="Screenshot 2023-08-22 at 3 07 00 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/5e80aae3-c455-4a24-9aa0-2eb77df51120">

## Test Plan
- [ ] Styling should still work across devices
- [ ] Functionality should still work (Click it -> is it on your clipboard ?)

## Issues
Closes #667

2023-08-22 11:26 UTC, ap0nia requested changes

2023-08-22 11:26 UTC, ap0nia commented on apps/antalmanac/src/components/Calendar/CourseCalendarEvent.tsx
> +                                            clickToCopy(event, sectionCode);
Since you're here, could you refactor `clickToCopy` to be a proper async function? I think we used `void` to get ESLint to ignore it so we can consume it as a synchronous function, but it should be async for clarity.

```ts
export async function clickToCopy(event: React.MouseEvent<HTMLElement, MouseEvent>, sectionCode: string) {
    event.stopPropagation();
    await navigator.clipboard.writeText(sectionCode)
    openSnackbar('success', 'WebsocSection code copied to clipboard');
}
```

The function is here: https://github.com/icssc/AntAlmanac/blob/main/apps/antalmanac/src/lib/helpers.ts#L333

The two consumers shouldn't be affected:
- https://github.com/icssc/AntAlmanac/blob/main/apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody.tsx#L110
- https://github.com/icssc/AntAlmanac/blob/main/apps/antalmanac/src/components/Calendar/CourseCalendarEvent.tsx#L180

2023-08-22 11:53 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/CourseCalendarEvent.tsx
> +                                            clickToCopy(event, sectionCode);
Done, also tested locally and it works!

2023-08-27 06:30 UTC, ap0nia approved these changes
Good

2023-08-27 06:31 UTC, merged