Course level select2
icssc/AntAlmanac pull request #677
Opened 2023-08-27 04:51 UTC by KevinWu098

## Summary
- Add Course Level filtering functionality. It's housed in the Advanced Search Options because it doesn't change the URL.
- I've also taken the liberty of moving the Online Classes label to `top` instead of the default (`right`), which fits more cleanly.

![Course Level Demo](https://github.com/icssc/AntAlmanac/assets/100006999/f72613a0-9d00-4432-b5a9-84f1247b8488)
_It's pretty blurry in this GIF, but upon selecting Upper Division Only, returned results are only those between 100 and 199 :D_

## Test Plan
- Make sure it works

## Issues
Closes #627

2023-08-27 08:29 UTC, MinhxNguyen7 requested changes
I haven't looked at the code yet, but I have some suggestions for the UI.

Some renaming for concision and taking up less space, especially on a mobile screen:
- "Course Level" -> "Level"
- "Any Course Division" -> "Any"
- "Lower Division Only" -> "Lower Division"
- "Upper Division Only" -> "Upper Division"
These shouldn't affect the comprehensibility of the feature because the removed words can be easily implied from context

The advanced search menu now looks pretty disorganized. It's especially hard to parse on mobile. I'd say that they should be more vertically organized or at least grouped more intentionally. You'll notice that it is the latter in the current version on mobile, especially.
![image](https://github.com/icssc/AntAlmanac/assets/64875104/a5854309-dded-4c06-96c2-cc08d9aedc6c)

The filter doesn't apply to the fuzzy search. I realized that this is consistent with the other fields, so this should be changed (or declared a feature) in a separate PR.

2023-08-27 09:23 UTC, KevinWu098 commented
> I haven't looked at the code yet, but I have some suggestions for the UI.
> 
> Some renaming for concision and taking up less space, especially on a mobile screen:
> 
> * "Course Level" -> "Level"
> * "Any Course Division" -> "Any"
> * "Lower Division Only" -> "Lower Division"
> * "Upper Division Only" -> "Upper Division"
>   These shouldn't affect the comprehensibility of the feature because the removed words can be easily implied from context
> 
> The advanced search menu now looks pretty disorganized. It's especially hard to parse on mobile. I'd say that they should be more vertically organized or at least grouped more intentionally. You'll notice that it is the latter in the current version on mobile, especially. ![image](https://user-images.githubusercontent.com/64875104/263516687-a5854309-dded-4c06-96c2-cc08d9aedc6c.png)
> 
> The filter doesn't apply to the fuzzy search. I realized that this is consistent with the other fields, so this should be changed (or declared a feature) in a separate PR.

I agree with you about the concision, but I do want to push back on `Course Level -> Level` and `Any Course Division -> Any`. 

- I think `Course Level -> Level` sacrifices too much readability for being concise. Compared to its next-door neighbors like `Online Classes Only` and `Class Full Option`, I think it's probably the least offensive of the three. 

  - Side note, but `Online Classes Only` could probably be renamed to `Online Only`... It's also somewhat out of place as a switch element amongst a few of Selects, but I don't have any ideas currently about making it feel more cohesive.

- This is more of a nitpick, but `Any` is just so much shorter than its counterparts and just makes it feel... unbalanced? This is probably a little over-subjective, but I think it's worth bringing up. 

In the meanwhile, I'll fiddle around with some divs and see if we can clean this up :)

2023-08-27 10:15 UTC, KevinWu098 commented
I'm pretty happy with how it's been cleaned up by getting rid of space-around in favor of a left-side oriented wrapping using gap. LMK how it looks :D @MinhxNguyen7

2023-08-30 02:25 UTC, MinhxNguyen7 approved these changes
LGTM!

2023-08-30 02:25 UTC, merged