Fix: Patch Notes didn't set Local Storage value
icssc/AntAlmanac pull request #692
Opened 2023-09-09 20:32 UTC by KevinWu098

## Summary
The refactored patch notes in #569 didn't set the local storage value when the patch notes dialog was closed. I've opted to reintroduce `useEffect` to check for `isOutdated` and set local storage if false. 

![Fix Demo](https://github.com/icssc/AntAlmanac/assets/100006999/fe43595f-304f-46c4-a5e0-4fa7ffa228dd)

Caption: Setting `latestPatchSeen` to `20230817` makes the dialog reappear and local storage to be set to `20230819` on refresh. 

## Test Plan
- [] Is local storage being set properly
- [] Dialog still closes fine
- [] Dialog doesn't reappear

## Issues
Closes #

2023-09-09 20:58 UTC, ap0nia requested changes
Write the data to local storage when the "close" button is clicked. When they hit "close" it's like a confirmation that they've "read the patch notes". Also, would you like to try writing a test for this, or would you like me to write one?

### Mini-rant
In general, it's good to be mindful of what certain actions mean, and what's happening in the code in relation to what the user is doing. 

For example (a real one that some smooth brain committed to the codebase), if a user clicks on a button to load a schedule, and the dialog closes after this process is done ... You don't "load the schedule" in relation to when the dialog closes. You load the schedule when the button is clicked, because that's when the user expects something to happen; the dialog closing is a side effect and not indicative of what the user originally did. For your sanity as much as the user's, make things happen in the program when you'd expect them to happen as a user.

2023-09-09 21:01 UTC, ap0nia commented
Honestly, I'm pretty sure you can use `handleClick` for both. i.e. remove the original  `handleClose`, rename `handleClick` to `handleClose`, and use that as the `onClose` prop for the `Dialog`, and as the `onClick` prop for the `Button`.

2023-09-09 21:02 UTC, KevinWu098 commented
> Write the data to local storage when the "close" button is clicked. When they hit "close" it's like a confirmation that they've "read the patch notes". Also, would you like to try writing a test for this, or would you like me to write one?
> 
> ### Mini-rant
> In general, it's good to be mindful of what certain actions mean, and what's happening in the code in relation to what the user is doing. 
> 
> For example (a real one that some smooth brain committed to the codebase), if a user clicks on a button to load a schedule, and the dialog closes after this process is done ... You don't "load the schedule" in relation to when the dialog closes. You load the schedule when the button is clicked, because that's when the user expects something to happen; the dialog closing is a side effect and not indicative of what the user originally did. For your sanity as much as the user's, make things happen in the program when you'd expect them to happen as a user.

It'll take me a little bit as I'm away from my laptop, but I'd like to attempt writing a tests for this! 

In regards to writing when it's closed, I'm unsure why handleClose, more specifically useCallback, isn't writing to local storage.

2023-09-09 21:03 UTC, ap0nia commented
That's because we literally forgot to put it there lol 
![image](https://github.com/icssc/AntAlmanac/assets/66761366/8a1ee8d4-5b1b-4f9c-9d06-dc60db0a964c)

2023-09-09 21:06 UTC, KevinWu098 commented
> That's because we literally forgot to put it there lol 
> 
> ![image](https://github.com/icssc/AntAlmanac/assets/66761366/67428f26-dfba-4c2f-b693-32a9ad82ac4f)

It was there originally:

![image](https://github.com/icssc/AntAlmanac/assets/100006999/a6e49699-c86e-4303-8250-a43964088f8b)

2023-09-10 03:43 UTC, ap0nia commented on apps/antalmanac/src/components/PatchNotes.tsx
>      }, [setOpen]);
```suggestion
    }, []);
```

2023-09-11 19:51 UTC, ap0nia requested changes
Good job getting the tests setup :fire:

Left some suggestions on implementation.

2023-09-11 19:51 UTC, ap0nia commented on apps/antalmanac/tests/setup.ts
You can remove this file if it's not being used.

2023-09-11 19:51 UTC, ap0nia commented on apps/antalmanac/vitest.config.ts
> +        // setupFiles: './tests/setup.ts',
You can remove this if we don't need it.

```suggestion
```

2023-09-11 19:51 UTC, ap0nia commented on apps/antalmanac/tests/patch-notes.test.tsx
> +describe('PatchNotes Component', () => {
I think this description is fine.
```suggestion
describe('patch notes', () => {
```

2023-09-11 19:51 UTC, ap0nia commented on apps/antalmanac/tests/patch-notes.test.tsx
> +import { describe, expect, it } from 'vitest';
I prefer `test` instead of `it`.

```suggestion
import { describe, test, expect } from 'vitest';
```

2023-09-11 19:51 UTC, ap0nia commented on apps/antalmanac/tests/patch-notes.test.tsx
> +            }
No, this shouldn't be handling any sort of rendering logic; that defeats the purpose of testing the component. The value of local storage should be manipulated, and the component should be verified to do the correct behavior depending on the value in local storage.

i.e. if we change the value in local storage to be different from the latest patch notes, then we expect no dialog to appear if the patch notes is rendered.

2023-09-11 20:19 UTC, KevinWu098 commented on apps/antalmanac/vitest.config.ts
> +        // setupFiles: './tests/setup.ts',
Whoops, I forgot that I had it commented out. The setup.ts file is needed as the tests will break if the JSDom isn't cleaned up after each test 😅

2023-09-11 20:42 UTC, KevinWu098 commented
Not sure why tests are failing on the GH-Actions; My guess is that it's not running them in `apps/AntAlmanac`?

Works on my machine<sup>tm</sup>. LMK if there's anything I can do/fix to make the tests run!

2023-09-12 00:23 UTC, ap0nia approved these changes
Epic :rocket:

2023-09-12 00:23 UTC, ap0nia commented on README.md
> +1. Run `pnpm test` in the root directory
You can also run `pnpm -w test` from any subdirectory. But I don't really care about the readme lol. Figure it out or it's a skill issue 🤓

2023-09-12 00:23 UTC, merged