Updated the logic of parsing for letterGrades
icssc/AntAlmanac pull request #731
Opened 2023-10-13 01:33 UTC by JackyZzZz

## Summary
Added Lettergrades to the x-axis of zotistics preview grade table.
![image](https://github.com/icssc/AntAlmanac/assets/110846941/731759f0-3dc5-4487-92bd-2c59f4e4b8f6)

## Test Plan
Make sure each Letter grade displays correctly under its associated bar. 
## Issues
Closes #728

## Future Followup
We might want to update the parsing logic once a while. I believe the parsing logic was correct before, but the data format from Zotistics might changed after that.

2023-10-13 16:53 UTC, EricPedley commented
@stevenguyukai this is a pretty simple one so I'm gonna leave the review completely to you. Message me on Discord if you have any questions.

2023-10-16 04:18 UTC, Douglas-Hong commented
It looks like #671, which was merged in very recently, added the labels for the x-axis in the graph:

![image](https://github.com/icssc/AntAlmanac/assets/78244965/166c8403-bc1b-45b1-9fda-3dc52c51b531)

@EricPedley maybe close this PR?

2023-10-18 06:36 UTC, EricPedley commented
I think we can salvage this one. @JackyZzZz can you just modify this PR so the only change is pulling the value for `name` out into `letterGrade` but preserving the string parsing logic as it currently is on `main`? Or just close this if you don't feel like doing that, since that basically reduces this PR to a two-line refactor.

2023-10-18 06:37 UTC, EricPedley requested changes
See my previous comment

2023-10-20 22:35 UTC, closed without merging