fix: refresh button refetches courses
icssc/AntAlmanac pull request #750
Opened 2023-10-19 18:30 UTC by ap0nia

## Description
Refresh button re-fetches courses

## Issues

Closes #736

2023-10-19 18:31 UTC, EricPedley approved these changes

2023-10-19 22:57 UTC, MinhxNguyen7 requested changes
Still nothing seems to happen when I click the refresh button. Not sure if I'm missing something

2023-10-19 23:25 UTC, ap0nia commented
There were multiple websoc caches in the app 🤦

2023-10-22 03:39 UTC, KevinWu098 reviewed
LGTM otherwise

2023-10-22 03:39 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/CoursePane/CourseRenderPane.tsx
> +    console.log('id: ', props.id);
```suggestion
```

Living rent-free 🤭

2023-10-26 07:19 UTC, MinhxNguyen7 approved these changes
LGTM!

I think the multiple caches might've been me. I vaguely remember extracting part of `helpers` into `course-helpers`, but I probably forgot to delete the old stuff. I'll make an issue for that.

2023-10-27 02:17 UTC, EricPedley commented
Bruh why does it still say there are conflicts 😭

2023-10-27 02:35 UTC, EricPedley approved these changes
approving my own additions to the PR to give me the green merge button (?)

2023-10-27 02:37 UTC, EricPedley commented
needs another review for nice green approval button

2023-10-27 03:26 UTC, KevinWu098 approved these changes
Trusting @EricPedley on this one! Gonna leave the final merge to someone else though, since I haven’t looked at the code much 🤭

2023-10-27 03:26 UTC, merged