Fix the duplicate calendar events bug
icssc/AntAlmanac pull request #818
Opened 2023-11-30 00:43 UTC by JacE070

## Summary
This change fixes the bug caused by looping over events' location.days when the calendarizeHelper has already returned events for each day.
For example, class A occurs every MWF, the calendarizeHelper returns **(event for Monday)** -> {..., location: {..., days: "MWF"}}, also events for **Wednesday** and **Friday** with the same location field.
Therefore, we will finally get 3*3=9 calendar events.
Finals are also added repetitively.
## Test Plan
Passed the vite test. Also tested manually.
## Issues

Closes https://github.com/icssc/AntAlmanac/issues/816

2023-11-30 14:13 UTC, ap0nia requested changes
Everything looks solid 👍 

I left some suggestions for minor improvements. Once you've taken a look at everything, this should be totally fine to merge. :rocket:

2023-11-30 14:13 UTC, ap0nia commented on apps/antalmanac/src/lib/download.ts
> +    events = [...AppStore.getEventsInCalendar(), ...AppStore.getFinalEventsInCalendar()]
Can you extract this to a dedicated function? I think it might even exist. Shorter function signatures is easier to read.

2023-11-30 14:13 UTC, ap0nia commented on apps/antalmanac/src/lib/download.ts
>                      if (location.days === undefined) return null;
This should be enforced by the linter, so this change is purely personal preference. After reading through lots of code, I really like it when things are consistent, even if they're marginally more verbose. I get throw off sometimes when reading through a bunch of if-statements with newlines and curly braces and then coming across one if-statement that's compacted into one line.

```suggestion
                    if (location.days === undefined) {
                      return null;
                    }
```

2023-11-30 14:13 UTC, ap0nia commented on apps/antalmanac/src/lib/download.ts
> +                            endOutputType: 'local' as const,
An improvement would be to capture these strings as their own constants or enums.

```ts
const CALENDAR_ID = 'antalamanc/ics'
const CALENDAR_OUTPUT = 'local' as const
```

2023-11-30 14:13 UTC, ap0nia commented on apps/antalmanac/src/lib/download.ts
> +                            end: getExamTime(finalExam, getYear(term))[1]!,
This is a blunder, don't call the same function twice for the same info. You can correctly extract all the data with the following snippet:

```ts
const [ start = '', end = '' ] = getExamTime(finalExam, getYear(term))

return {
  // ...
  end,
  start
}
```

Use array destructuring to immediately assign meaningful names to the variables, and then give them a default value of empty string if they're missing.

2023-11-30 14:13 UTC, ap0nia commented on apps/antalmanac/src/stores/calendarizeHelpers.ts
> +                                days: meeting.days === null ? undefined : COURSE_WEEK_DAYS[dayIndex],
This seems a bit misleading, because `meeting.days` shouldn't be set to null manually? You didn't change this code, but it would be more appropriately captured as 
```suggestion
                                ...(meeting.days && { days: COURSE_WEEK_DAYS[dayIndex] })
```

Logic: 
The statement will either return something falsy (null, undefined, false, etc.) or an object with the `days` property.
When you destructure a falsy object, it doesn't return anything. When you destructure an actual object, its properties get inherited by the parent object

```ts
const myObject = { hello: 'world', ...(false) }
// myObject = { hello: 'world' }

const myOtherObject = { hello: 'world', ...({ goodbye: 'earth' }) }
// myOtherObject = { hello: 'world', goodbye: 'earth' }
```

2023-12-04 06:32 UTC, JacE070 commented on apps/antalmanac/src/stores/calendarizeHelpers.ts
> +                                days: meeting.days === null ? undefined : COURSE_WEEK_DAYS[dayIndex],
Makes sense. Glad to know this!

2023-12-05 18:36 UTC, EricPedley approved these changes
since this is a bugfix, imma just merge it real quick. @ap0nia if u want anything else to be refactored we can do it in a separate PR.

2023-12-05 18:36 UTC, merged