Added copy button to schedule dropdown
icssc/AntAlmanac pull request #829
Opened 2023-12-04 00:31 UTC by JackyZzZz

## Summary
Added the copy schdule column to schedule dropdown
## Test Plan
Test locally, LGTM
## Issues
Closes #804

2023-12-04 02:15 UTC, KevinWu098 requested changes
Thanks for implementing the feature -- just a handful of small implementation issues

Additionally, I'm going to ask that you refactor `AddedCoursePane` to utilize this new implementation

2023-12-04 02:15 UTC, KevinWu098 commented on apps/antalmanac/src/components/dialogs/CopySchedule.tsx
> +    const { index, onClose } = props;
Separately destructure onClose please; (Reference `DeleteSchedule.tsx` or ask Brian if curious why)

```suggestion
    const { index } = props;
    
     /**
     * This is destructured separately for memoization.
     */
    const { onClose } = props;
```

2023-12-04 02:15 UTC, KevinWu098 commented on apps/antalmanac/src/components/dialogs/CopySchedule.tsx
> +                <Button onClick={onClose} color="inherit">
Instead of directly using onClose, use a handler like in `DeleteSchedule.tsx`, for typing purposes

2023-12-04 02:15 UTC, KevinWu098 commented on apps/antalmanac/src/components/dialogs/CopySchedule.tsx
> +    const handleScheduleChange = useCallback((event: React.ChangeEvent<{ value: unknown }>) => {
More accurate type
```suggestion
    const handleScheduleChange = useCallback((event: SelectChangeEvent<number>) => {
```

2024-02-07 21:47 UTC, KevinWu098 requested changes
Thanks for implementing the changes, but there are still a few code quality and bugs hanging around.

Aside from the diff itself, the changes to `CopyScheduleButton` are causing errors down in `AddedSectionsGrid` because the button now requires an index prop which is not provided.

Also not in the diff -- but might as well handle it here -- `createCopyHandler` is unused (and likely has been unused for sometime) so we might as well nix it.

2024-02-07 21:47 UTC, KevinWu098 commented on apps/antalmanac/src/components/dialogs/CopySchedule.tsx
> +    }, [onClose, index]);
```suggestion
    }, [onClose]);
```
exhaustive-deps

2024-02-07 21:47 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
> +function CopyScheduleButton(props: { index: number }) {
```suggestion
function CopyScheduleButton(index: number) {
```
No need to use a props object for one prop

2024-02-07 21:47 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
> +            <CopyScheduleDialog fullWidth open={open} index={props.index} onClose={handleClose} />
```suggestion
            <CopyScheduleDialog fullWidth open={open} index={index} onClose={handleClose} />
```
Follow-up change from above w/ props

2024-02-07 21:47 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
>  import { Box, Chip, IconButton, Menu, MenuItem, Paper, SxProps, TextField, Tooltip, Typography } from '@mui/material';
```suggestion
import { Box, Chip, IconButton, Paper, SxProps, TextField, Tooltip, Typography } from '@mui/material';
```
Unused import

2024-02-19 01:19 UTC, JackyZzZz commented
@ap0nia Looks like there is something wrong with the deployment :-) any idea on it maybe lol

2024-02-19 01:23 UTC, KevinWu098 commented
> @ap0nia Looks like there is something wrong with the deployment :-) any idea on it maybe lol

Looks like it's because a staging deploy already existed here: https://staging-829.antalmanac.com/, which was prior to the new devops stuff?

I'm okay with locally testing this PR btw

2024-02-19 01:28 UTC, KevinWu098 requested changes
Overall looks solid, thanks for working on the feature! Like we discussed on Friday, it's just the one bug (for now) that I've noted in the comment below, but I'll do a final comprehensive sweep over the PR once that's fixed.

2024-02-19 01:28 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
Impossible for me to comment on line 365 (it's not in the diff), specifically `CopyScheduleButton />` , but it needs to be passed an index prop, now that the component, `CopyScheduleDialog` is updated to require an index prop.

2024-04-02 21:58 UTC, MinhxNguyen7 commented
@JackyZzZz so close to merging 🤏

2024-04-22 20:39 UTC, KevinWu098 approved these changes
LGTM; Will also note that CalendarToolbar and AddedCoursePane now have 2 sets of buttons (clear, copy) which are virtually identical, but implemented twice.

Should look to unify these in a future PR

2024-04-22 20:39 UTC, merged