feat: create hover view
icssc/AntAlmanac pull request #836
Opened 2023-12-07 01:39 UTC by KevinWu098

## WIP
- [ ] Show all meetings of the section
- [ ] Handle hovered sections that are already added
- [ ] Disable in added pane (possibly solved by task 2)
- [ ] Make not an eyesore

## Summary
1. Implement a `HoveredStore` to store the currently hovered course
2. `SectionTableBody` will access and update `HoveredStore` when a section is hovered
3. Hovered Courses will be appended to events passed to the Calendar

![chrome-capture-2023-11-6](https://github.com/icssc/AntAlmanac/assets/100006999/8a6eca72-5008-4250-bb00-0d90a7c03c74)

## Test Plan

## Issues
Closes #828

2023-12-07 06:51 UTC, EricPedley reviewed
Code looks fine, but I think the classes instantly showing up looks a little jarring. I think we should add a delay before the class shows up previewed on the calendar and maybe an animation to fade it in. We can bring this up in the meeting tomorrow to get more input on what to do from a UI/UX perspective here.

2023-12-08 08:50 UTC, KevinWu098 commented
TL;DR of latest changes:

1. "Hovered" courses are now 80% opacity
2. Settings Menu has some updated styling
3. Preview Mode is now in settings menu, defaulting false

I've chosen not to move Schedule Conflict into the experimental menu, as after some further thought, I agree with Eric on that it's a feature people have gotten used to, but I'm happy to circle back to that as needed

2024-01-24 04:39 UTC, EricPedley requested changes
Ok one more small change: can we call the toggle in the settings menu "Hover to Preview" instead of "Preview Mode"? I think it makes it more clear what it does. LMK if you agree or not. After we decide this, good to merge.

2024-01-24 21:13 UTC, EricPedley approved these changes

2024-01-24 21:37 UTC, merged