Display Finals Date From Default Term
icssc/AntAlmanac pull request #881
Opened 2024-02-05 23:45 UTC by adcockdalton

## Summary

1. Added new optional field to TermData.ts "finalsStartDate"
2. Changed calendarizeFinals to correctly assign finals to their respective dates instead of the arbitrary (2018, 0, 1)
3. Refactored CalendarRoot to use date instead of defaultDate
4. Dynamically update date

Regular classes still populate to the arbitrary 2018 date, which is simpler since those are displayed dateless. All other data relies on the finalsStartDate field specified by defaultTerm.

## Test Plan

1. Make a schedule with classes that have different finals, toggle back and forth.
2. Try with only Saturday finals classes (Math 2b) or a mix of each (any class and Math 2b), etc.

## Issues

Closes #758 

## Future Followup
Make an alternate to hardcoding future dates (#778) including for finals, or at least hardcode the next few years.

2024-02-06 09:00 UTC, KevinWu098 requested changes
Great PR, looking forward to using this feature.

Some minor refactoring suggestions and code questions, but otherwise looks great!

2024-02-06 09:00 UTC, KevinWu098 commented on apps/antalmanac/src/stores/calendarizeHelpers.ts
Why is this file updated to use the `defaultFinalsStart()` values?

2024-02-06 09:00 UTC, KevinWu098 commented on apps/antalmanac/src/lib/termData.ts
> +function getDefaultFinalsStartDate() {
If there's no `finalsStartDate`, I think it would be preferable to return `undefined`, rather that the hardcoded values

2024-02-06 09:00 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/CalendarRoot.tsx
> +    const date = showFinalsSchedule ? defaultFinals : new Date(2018, 0, 1);
```suggestion
    const date = defaultFinals ?? new Date(2018, 0, 1);
```
If finals aren't being shown, the value of date doesn't matter, so this can be simplified. 

_The code above is also written assuming you choose to return `undefined` from `getDefaultFinalsStartDate()` like described below. The unneeded `showFinalsSchedule` is still true no matter what, unless I've missed something (very possible!)._

2024-02-06 09:00 UTC, KevinWu098 commented on apps/antalmanac/src/lib/termData.ts
> +}
```suggestion
function getDefaultFinalsStartDate(): Date | undefined {
    const [year, month, day] = termData[defaultTerm].finalsStartDate || [];

    return year && month && day ? new Date(year, month, day + 1) : undefined;
}
```
Additionally, it might be better to refactor so that you're not accessing a "magic" array -- all values should (ideally) tell you what they are

2024-02-06 09:04 UTC, KevinWu098 commented on apps/antalmanac/src/components/Calendar/CalendarRoot.tsx
> +    const date = showFinalsSchedule ? defaultFinals : new Date(2018, 0, 1);
```suggestion

    const calendarStyling = isMobile ? { height: `calc(100% - 55px)` } : { height: `calc(100vh - 104px)` };
    
    const calendarTimeFormat = isMilitaryTime ? 'HH:mm' : 'h:mm A';
    const calendarGutterTimeFormat = isMilitaryTime ? 'HH:mm' : 'h A';
    
    const defaultFinals = getDefaultFinalsStartDate();
    const finalsDateFormat = defaultFinals ? 'ddd MM/DD' : 'ddd';
    const date = showFinalsSchedule ? defaultFinals : new Date(2018, 0, 1);
```

Honestly, this is a total nitpick (not your fault/not related to this PR), and could be a code smell, but I'd like to break up some of these values so it's more immediately clear what is related to what.

2024-02-06 21:30 UTC, adcockdalton commented on apps/antalmanac/src/stores/calendarizeHelpers.ts
Apologies if I was not clear enough on point 2; I can explain more on that: 

RBC, as we are implementing it now, populates the calendar with events that are assigned specific days. Prior to this PR, every event, class, final etc. populates on the first week of January 2018 for whatever reason. However, to get the finals to display with the correct actual dates, we have to set the date to the start date of finals (adjusted by 1 to show the correct week regardless of a Saturday final) so that the current viewed week is the correct finals week when toggled rather than the first week of January 2018. That's just how RBC works unfortunately... 

So what I did is, if the defaultFinalsStart exists, is assign the finals to the actual week they occur on. Then if showFinalsSchedule is on you will actually see the dates.

This is also why I can't simplify the logic with showFinalsSchedule like you suggested in the other comment: if we do so, then you will not see any classes because the classes only show up in 2018.

lmk if there are any more questions on that, it was annoying figuring it all out haha

2024-02-06 21:31 UTC, adcockdalton commented on apps/antalmanac/src/stores/calendarizeHelpers.ts
making a push with the other changes you suggested in about 20 minutes once I finish a quiz 👍

2024-02-06 22:01 UTC, adcockdalton commented on apps/antalmanac/src/stores/calendarizeHelpers.ts
If it helps to demo, observe the default behavior by removing the hardcoded finals date from the winter 2024 term in termdata.ts

2024-02-06 22:22 UTC, KevinWu098 commented on apps/antalmanac/src/stores/calendarizeHelpers.ts
Gotcha, thanks for explaining it to me

2024-02-06 22:28 UTC, KevinWu098 approved these changes
LGTM, thanks for working on this! r🚀

There's probably some more discussion to be had about how to handle other terms than the current one, but that's out of scope for this PR (and is likely gated behind Google Auth).

I'll approve but not merge for now, as I want to confirm the final implementation at the sprint this Wednesday

2024-02-06 22:29 UTC, KevinWu098 requested changes
Whoops! Sike, not LGTM.

@adcockdalton, you get to now enjoy writing tests. The `calendarize-helpers` test is failing (should be quick fix), but that'll need to get done before we can merge.

2024-02-07 21:08 UTC, KevinWu098 approved these changes
LGTM; bit loathe to use a hardcoded test for a changing value but I can live with it (we'll just deal with it later TM)

2024-02-07 21:11 UTC, merged