fix: show recruitment banner again
icssc/AntAlmanac pull request #918
Opened 2024-02-21 02:22 UTC by KevinWu098

## Summary
1. The change to pass search queries as lowercase in #755 resulted in the Recruitment Banner never showing up, as the banner checked for *uppercase* queries, which are now *lowercase*.
2. Use `.toUpperCase()` on the value we grab from `RightPaneStore`

## Test Plan
1. Go into Chrome Dev Tools and the application tab to clear your `recruitmentDismissalTime`. Then search for COMPSCI and see if it pops up.

2024-02-21 08:02 UTC, EricPedley requested changes
![image](https://github.com/icssc/AntAlmanac/assets/48658337/9d10eeca-f3c6-4eaa-886a-d827d48a3420)
It overlaps with the restart tutorial button :(
Any ideas for how to fix this? My first thought would to be moving the recruitment banner up a little bit with some css.

2024-02-21 08:13 UTC, KevinWu098 commented
> ![image](https://github.com/icssc/AntAlmanac/assets/48658337/9d10eeca-f3c6-4eaa-886a-d827d48a3420)
> 
> It overlaps with the restart tutorial button :(
> 
> Any ideas for how to fix this? My first thought would to be moving the recruitment banner up a little bit with some css.

Could always move the tutorial up a few pixels 🏃‍♂️

2024-02-24 09:39 UTC, KevinWu098 commented
> ![image](https://private-user-images.githubusercontent.com/48658337/306543340-9d10eeca-f3c6-4eaa-886a-d827d48a3420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDM2MjYsIm5iZiI6MTcwODUwMzMyNiwicGF0aCI6Ii80ODY1ODMzNy8zMDY1NDMzNDAtOWQxMGVlY2EtZjNjNi00ZWFhLTg4NmEtZDgyN2Q0OGEzNDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA4MTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YTg2YzI5MWExNWExMDU4NzAxZTE4NjNkMTk1YThjYzM0NWRhZDZjYWQ3M2U3ZTFjYjFiZDY2ZTRhNWNiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qmbf6hLQ-hzyI96BuNQ2Ht6FDJjRIwMEGJyb8y2Q0dE) It overlaps with the restart tutorial button :( Any ideas for how to fix this? My first thought would to be moving the recruitment banner up a little bit with some css.

Above:
<img width="960" alt="Screenshot 2024-02-24 at 1 38 19 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/d5a9cb8a-1c94-49fd-9301-2d6d7f0f1ea9">

Left:
<img width="960" alt="Screenshot 2024-02-24 at 1 39 20 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/fae60f1b-5478-4f12-89a8-4513711a0b69">

It looks kinda wonky both ways tbh but any thoughts? @EricPedley

2024-02-28 21:53 UTC, EricPedley commented
on the left looks good

2024-02-28 22:01 UTC, EricPedley approved these changes

2024-02-29 03:51 UTC, merged