feat: one tab mobile layer
icssc/AntAlmanac pull request #921
Opened 2024-02-24 10:17 UTC by KevinWu098

## Summary
1. Simplify our tab layout by removing the Calendar / Classes split in favor of Calendar / Search / Added / Map

## Test Plan
1. UI testing

## Issues
Closes #795

2024-03-13 20:21 UTC, KevinWu098 commented
Reminder: update the tutorial so that it hooks onto something other than the desktop tabs

2024-04-21 21:00 UTC, MinhxNguyen7 commented
@KevinWu098 How this looking? Also, the tutorial shouldn't show on mobile, so I'm not sure what you're referring to.

2024-04-22 00:39 UTC, KevinWu098 commented
> @KevinWu098 How this looking? Also, the tutorial shouldn't show on mobile, so I'm not sure what you're referring to.

I'll start back up on this PR this week; the comment above is referencing how the Tutorial is positioned to the RightPane, which the current implementation on this branch is reusing for mobile (and thus causing it to show up on mobile).

2024-04-27 21:24 UTC, MinhxNguyen7 commented on apps/antalmanac/src/components/Map/Map.tsx
> -            AppStore.removeListener('currentScheduleIndexChange', updateCalendarEvents);
Why is this listener not removed anymore when it's still being added above?

2024-04-27 21:25 UTC, MinhxNguyen7 commented on apps/antalmanac/src/components/Map/Map.tsx
> -        AppStore.on('customEventsChange', updateCalendarEvents);
Why is this being removed? Everything seems to work fine, so I guess it wasn't necessary but why is that the case?

2024-04-27 21:27 UTC, MinhxNguyen7 requested changes
Very nice. Looks great. I do think that the bar should be at the bottom, but it's up to you if you want it to be.

I only have the concern about the listener.

2024-04-29 17:21 UTC, KevinWu098 commented
> Very nice. Looks great. I do think that the bar should be at the bottom, but it's up to you if you want it to be.
> 
> I only have the concern about the listener. Also, while you're at it, can you resolve the merge conflict?

Issues are resolved.

I also agree that the button should be on the bottom, but that change carries a host of styling fixes and adjustments and I'd rather do those in a follow-up PR. We can discuss @ sprint

2024-04-29 22:22 UTC, MinhxNguyen7 approved these changes
LGTM!

2024-04-29 22:23 UTC, merged