Add dismiss help box functionality
icssc/AntAlmanac pull request #923
Opened 2024-02-26 00:07 UTC by Douglas-Hong

## Summary
- The help box now has a close button on the upper-right corner and is dismissible.
- The help box can only be shown on these months: February/March for Spring planning, May/June for Fall planning, August for Summer planning, and November/December for Winter planning.
- If 30 days has passed since the last time the user dismissed the help box AND the current month is still an active month, then the help box will be displayed again.
- Any feedback is appreciated for the active months and the 30 day dismissal threshold.

## Test Plan
- Make sure the help box is never shown during inactive months.
- Change the 30 day threshold to something really small, and see if the help box comes back on an active month.

## Issues

Closes #652

2024-02-27 08:28 UTC, EricPedley approved these changes
lgtm but I'm gonna wait for @KevinWu098 to look before merging since he opened the original issue and there's a bunch of discussion on there I don't wanna read 😅

2024-02-27 09:04 UTC, KevinWu098 commented
> lgtm but I'm gonna wait for @KevinWu098 to look before merging since he opened the original issue and there's a bunch of discussion on there I don't wanna read 😅

Agreed, also LGTM but...

Freshmen, who are most likely to need the help box, begin planning in July (possibly even June) and SPOPs occur between July-August, so we might want to toss July on the list of active months as well.

Gotta lookout for us younglings 🙏

2024-02-27 09:05 UTC, KevinWu098 requested changes

2024-02-27 09:05 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/SearchForm.tsx
> +    const activeMonthIndices = [false, true, true, false, true, true, false, true, false, false, true, true];
```suggestion
    const activeMonthIndices = [false, true, true, false, true, true, true, true, false, false, true, true];
```

Add July to active months for SPOPs

2024-02-28 21:07 UTC, KevinWu098 approved these changes
LGTM

2024-02-28 21:10 UTC, merged