Display "No Courses Added Yet" when list of added classes is empty
icssc/AntAlmanac pull request #924
Opened 2024-02-26 20:12 UTC by ollykel

## Summary

Adds a "No Courses Added Yet!" notification in the right pane for Added courses when the list of added classes is empty.

![Screenshot from 2024-02-26 12-06-45](https://github.com/icssc/AntAlmanac/assets/24789977/a9bc98ca-4fff-4935-a111-945a28bef395)

## Test Plan

Start from an empty schedule, add classes, then remove classes until the schedule is empty again. "No Courses Added!" should appear under the schedule name if and only if the list of added classes is empty.

## Issues

Closes #922

2024-02-26 21:29 UTC, Douglas-Hong commented
Thanks for tackling this issue! I think it would be a good idea to add some more styling, such as centering the text and adding some padding around it. @KevinWu098 do you have any opinions about this?

2024-02-26 21:59 UTC, KevinWu098 requested changes
Thank you for working on this issue! I agree w/ @Douglas-Hong, I think it would be best to add some additional padding and styling.

One possible avenue would be to have it styled similarly to the ScheduleNoteBox (in terms of size and padding), but I'm sure most approaches would be fine.

2024-02-26 21:59 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
> +                {courses.length < 1 ? <Typography variant="h7">No Courses Added Yet!</Typography> : <></>}
```suggestion
                {courses.length < 1 ? <Typography>No Courses Added Yet!</Typography> : <></>}
```
I don't believe `h7` is a valid variant; If you're going for a `<p>` tag, I don't believe the variant prop is necessary.

2024-02-27 00:43 UTC, ollykel commented
Thank you for the feedback!

This is what is looks like with align="center" and padding="1.5px". Does it look alright? Also, is there a preferable way to add styling to elements?

![Screenshot from 2024-02-26 16-39-44](https://github.com/icssc/AntAlmanac/assets/24789977/17677132-5462-4af3-8b4d-e2aa1441927d)

2024-02-27 01:37 UTC, KevinWu098 commented
> Thank you for the feedback!
> 
> This is what is looks like with align="center" and padding="1.5px". Does it look alright? Also, is there a preferable way to add styling to elements?
> 
> ![Screenshot from 2024-02-26 16-39-44](https://private-user-images.githubusercontent.com/24789977/307996971-17677132-5462-4af3-8b4d-e2aa1441927d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTc5MjEsIm5iZiI6MTcwODk5NzYyMSwicGF0aCI6Ii8yNDc4OTk3Ny8zMDc5OTY5NzEtMTc2NzcxMzItNTQ2Mi00YWYzLThiNGQtZTJhYTE0NDE5MjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAxMzM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZDk2MDUzMWZjZTJmYmIxNjQ2ZGM2MjQ4YjNiNDA1ZDc2YTcyYzExMmJkNDk1NTcwODY2M2FjZjY1MmI4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJvjana7HtZNzCN88a4Frv0Xdk_JOefHpjKVe6294C4)

Looks much better! Could you add a background that would span the entire space? The text currently looks a tad "orphaned", for lack of a better term.

And in regards to styling, we usually write our styles inline, although we don't necessarily strictly enforce how styling should be done.

2024-02-27 18:49 UTC, ollykel commented
Any preferences on background color?

Grey looks like this in dark mode and light mode:

![Screenshot from 2024-02-27 10-32-08](https://github.com/icssc/AntAlmanac/assets/24789977/2b3f07f1-9c1d-442f-93cb-fef027dcfc1b)

![Screenshot from 2024-02-27 10-32-21](https://github.com/icssc/AntAlmanac/assets/24789977/9cea9f5e-0907-48a9-91b3-bf62650f7b92)

Also changed the padding to 16px.

2024-02-28 19:25 UTC, ollykel commented
Just committed some tweaks @KevinWu098, should look like the screenshots I posted above.

2024-02-28 21:54 UTC, KevinWu098 requested changes
Thanks for the updates; we discussed the element at our latest sprint, and we think that it might be best to go simpler -- closer to the first iteration

Mainly for these reasons:
1. The current background/size might confuse a user, as it somewhat resembles the note box underneath
2. The color contrast is a little strong with dark gray on light gray

Something along the lines of 12px in top & bottom padding and left align is what we settled on:

<img width="905" alt="Screenshot 2024-02-28 at 1 53 56 PM" src="https://github.com/icssc/AntAlmanac/assets/100006999/906178a5-6e2f-4cc9-b8d5-11fd63067e01">

Sorry bout the back and forth, but we should be good to go after these suggested changes

2024-02-28 21:54 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
> +                {courses.length < 1 ? noCoursesNotif : <></>}
```suggestion
                {courses.length < 1 ? noCoursesNotif : null}
```

2024-02-28 21:54 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
> +    const noCoursesNotif = (
```suggestion
    const NoCoursesBox = (
```
Bit of a nit, but "Notif" might be the wrong way to phrase this element

2024-02-29 00:47 UTC, ollykel commented
No worries, thank you for the feedback.

I implemented the changes you requested, hopefully we should be good soon!

2024-02-29 01:53 UTC, KevinWu098 approved these changes
LGTM! Thanks for working on this 🚀 

Please squash and merge when you get a chance 💪

2024-02-29 04:30 UTC, ollykel commented
> LGTM! Thanks for working on this 🚀 
> 
> 
> 
> Please squash and merge when you get a chance 💪 

Thank you!

I don't have the right to merge, how should we move forward?

2024-02-29 04:39 UTC, KevinWu098 commented
> > LGTM! Thanks for working on this 🚀
> > Please squash and merge when you get a chance 💪
> 
> Thank you!
> 
> I don't have the right to merge, how should we move forward?

Whoops, forgot about that. I'll merge it in 🫡

2024-02-29 04:39 UTC, merged