Always display GPA Column
icssc/AntAlmanac pull request #980
Opened 2024-05-05 08:05 UTC by MinhxNguyen7

## Summary
- The GPA column will now be shown on both the search and added panes.
- Remove vestigial logic in the stores which enabled the disabling of the columns in the added pane.
- Fix a bug that broke the column toggle buttons. This was broken before, but no one noticed.

## Test Plan
- Check that the GPA column shows up in both panes.
- Check that the column toggles work as expected.

## Issues
- Closes #939 

## Future Followup
- Would be nice for the column filtering to persist between page loads.

2024-05-06 17:56 UTC, KevinWu098 requested changes
LGTM! Lookin' forward to having GPA column in the Added section 😋 

Just one chore and we're good to go!

2024-05-06 17:56 UTC, KevinWu098 commented on apps/antalmanac/src/components/RightPane/CoursePane/CoursePaneButtonRow.tsx
> +    console.log('selectedColumnNames', selectedColumnNames);
chore: remove console.log

2024-05-09 21:10 UTC, MinhxNguyen7 commented on apps/antalmanac/src/components/RightPane/CoursePane/CoursePaneButtonRow.tsx
> +    console.log('selectedColumnNames', selectedColumnNames);
oops

2024-05-09 21:50 UTC, KevinWu098 approved these changes
LGTM

2024-05-09 23:10 UTC, merged