fix: date formatting logic in enrollmentHistory for Safari
icssc/AntAlmanac pull request #987
Opened 2024-05-24 08:44 UTC by pinapelz

## Summary
Safari handles parsing dates differently than other browsers. Here is one way of fixing it by handling the date as a string before making it a Date object

I think you can also maybe using something like `date-fns` to handle the cross platform behavior for parsing dates (although I personally think that might be too overkill for just this one use case)

## Test Plan
Verified that the result is the same as what's on prod. Tested on Mac and iOS
![image](https://github.com/icssc/AntAlmanac/assets/21994085/8bd57a21-bca4-4e40-bcfa-464c420d28af)

## Issues

Closes #947

2024-05-24 16:45 UTC, ap0nia requested changes
Thanks, I was totally unaware of this fact! I left some suggestions, but I can put in some time to fix it myself later when I have the chance. 🚀

2024-05-24 16:45 UTC, ap0nia commented on apps/antalmanac/src/lib/enrollmentHistory.ts
> +                const d = new Date(Number(dateParts[0]), Number(dateParts[1]), Number(dateParts[2]));
Could you make the parts of the date a bit more descriptive?

```suggestion
                const [day='', month='', year='']= date.split('-');
                const date = new Date(Number(day), Number(month), Number(year));
```

2024-05-24 16:45 UTC, ap0nia commented on apps/antalmanac/src/lib/enrollmentHistory.ts
> +                const formattedDate = `${d.getMonth()}/${d.getDate() - 1}/${d.getFullYear()}`;
If there's no naming conflicts, could we use the variable `date`?
```suggestion
                const formattedDate = `${date.getMonth()}/${date.getDate() - 1}/${date.getFullYear()}`;
```

2024-05-24 19:26 UTC, pinapelz commented
I've applied the changes. There was a naming conflict with date so I renamed the date data taken from enrollmentHistory to dateString instead.

2024-05-26 18:40 UTC, ap0nia approved these changes
Looks good, I'll merge it when I'm able to 🎉

2024-05-26 23:35 UTC, merged